# 💻 Esercizi di Programmazione Python

In [109]:
import numpy as np
from fontTools.cffLib import maxStackLimit

### 1. Scrivi una funzione che prende una lista di interi e restituisce un dizionario con chiavi 'pari' e 'dispari'.

In [110]:

def fun(a:list) -> dict:
    dict_pd = {'pari': 0,
            'dispari': 0}
    for number in a:
        if number %2 == 0:
            dict_pd['pari'] += 1
        else:
            dict_pd['dispari'] +=1
    return dict_pd

# Test con vari casi
test1 = [1, 2, 3, 4, 5]  # 2 pari, 3 dispari
test2 = [2, 4, 6, 8]     # tutti pari
test3 = [1, 3, 5, 7]     # tutti dispari
test4 = []               # lista vuota

print("Test 1:", fun(test1))  # Dovrebbe dare {'pari': 2, 'dispari': 3}
print("Test 2:", fun(test2))  # Dovrebbe dare {'pari': 4, 'dispari': 0}
print("Test 3:", fun(test3))  # Dovrebbe dare {'pari': 0, 'dispari': 4}
print("Test 4:", fun(test4))  # Dovrebbe dare {'pari': 0, 'dispari': 0}


Test 1: {'pari': 2, 'dispari': 3}
Test 2: {'pari': 4, 'dispari': 0}
Test 3: {'pari': 0, 'dispari': 4}
Test 4: {'pari': 0, 'dispari': 0}


### 2. Scrivi una funzione che conta quante volte ogni carattere appare in una stringa.

In [111]:
def conta_carattere(s:str,c:str) -> int:
    count = 0
    for character in s:
        if character == c:
            count += 1
    return  count

# Test con vari casi
print(conta_carattere("hello", "l"))      # Dovrebbe dare 2
print(conta_carattere("python", "p"))     # Dovrebbe dare 1
print(conta_carattere("banana", "a"))     # Dovrebbe dare 3
print(conta_carattere("test", "x"))       # Dovrebbe dare 0
print(conta_carattere("", "a"))           # Dovrebbe dare 0
print(conta_carattere("AAA", "A"))        # Dovrebbe dare 3
print(conta_carattere("ciao mondo", " ")) # Dovrebbe dare 1

2
1
3
0
0
3
1


### 3. Scrivi una funzione che riceve una lista e restituisce True se tutti gli elementi sono diversi.

In [112]:
def div(lst:list) -> bool:
    num_prec = 0
    for num in lst:
        if num == num_prec:
            return False
        else:
            num_prec = num

    return True

# Test con vari casi
print(div([1, 2, 3, 4, 5]))  # Dovrebbe restituire True (tutti diversi)
print(div([1, 1, 2, 3, 4]))  # Dovrebbe restituire False (ci sono duplicati)
print(div([]))               # Dovrebbe restituire True (lista vuota)
print(div([7]))              # Dovrebbe restituire True (un solo elemento)
print(div([1, 2, 3, 3, 4]))  # Dovrebbe restituire False (duplicati consecutivi)

True
False
True
True
False


### 4. Scrivi una funzione che restituisce una lista con elementi unici, mantenendo l'ordine.

In [113]:
def elem_unic(lst:list) -> list:

    lst = set(lst)
    lst = list(lst)
    return lst

# Test con vari casi
print(elem_unic([1, 2, 2, 3, 4, 4, 5]))  # Dovrebbe restituire [1, 2, 3, 4, 5]
print(elem_unic([7, 7, 7, 7]))           # Dovrebbe restituire [7]
print(elem_unic([]))                    # Dovrebbe restituire []
print(elem_unic([1, 2, 3, 4, 5]))       # Dovrebbe restituire [1, 2, 3, 4, 5]
print(elem_unic([5, 4, 3, 2, 1, 1, 2])) # Dovrebbe restituire [5, 4, 3, 2, 1]

[1, 2, 3, 4, 5]
[7]
[]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


### 5. Scrivi una funzione one-liner che restituisce tutti i multipli di 5 in una lista.

In [114]:
def multiply_of_5(lst:list) -> list:
    return [number for number in lst if number %5 == 0]

# Test con vari casi
print(multiply_of_5([5, 10, 15, 20]))       # Dovrebbe restituire [5, 10, 15, 20]
print(multiply_of_5([1, 2, 3, 4]))          # Dovrebbe restituire []
print(multiply_of_5([0, 5, 25, 30, 7]))     # Dovrebbe restituire [0, 5, 25, 30]
print(multiply_of_5([-5, -10, 0, 3, 8]))    # Dovrebbe restituire [-5, -10, 0]
print(multiply_of_5([]))                    # Dovrebbe restituire []


[5, 10, 15, 20]
[]
[0, 5, 25, 30]
[-5, -10, 0]
[]


### 6. Scrivi una funzione che restituisce una lista dei quadrati dei numeri positivi.

In [115]:
def quadrati(lst:list) -> list:
    return [number **2 for number in lst if number > 0 ]

# Test con vari casi
print(quadrati([1, 2, 3, 4]))         # Dovrebbe restituire [1, 4, 9, 16]
print(quadrati([-1, 2, -3, 4]))       # Dovrebbe restituire [4, 16]
print(quadrati([-2, -1, 0]))          # Dovrebbe restituire []
print(quadrati([]))                   # Dovrebbe restituire []
print(quadrati([5, -5, 10, -10, 3]))  # Dovrebbe restituire [25, 100, 9]

[1, 4, 9, 16]
[4, 16]
[]
[]
[25, 100, 9]


### 7. Scrivi una funzione che restituisce il massimo numero di True consecutivi in una lista di booleani.

In [116]:
def max_num(lst:list) -> int:
      if len(lst) == 0:
          return 0
      count = 0
      max  = 0
      for i in range (0,len(lst)):
        if lst[i] == True:
            count +=1
            if count > max:
                max = count
        else:
            count = 0
      return max

# Test con vari casi
print(max_num([True, True, False, True]))          # Dovrebbe restituire 2
print(max_num([True, True, True, False]))          # Dovrebbe restituire 3
print(max_num([False, False, True, True]))         # Dovrebbe restituire 2
print(max_num([True]))                             # Dovrebbe restituire 1
print(max_num([False, True, False, True, True]))   # Dovrebbe restituire 2
print(max_num([False, False, False]))              # Dovrebbe restituire 0


2
3
2
1
2
0


### 8. Scrivi una funzione che prende due liste e restituisce True se una e la reversa dell'altra.

In [117]:
def reverse(lst1:list,lst2:list) -> bool:
    if len(lst1) != len(lst2):
        return False
    for i in range (0,len(lst1)):
        if lst1[i] != lst2[-1-i]:
            return False
    return True

# Test con vari casi
print(reverse([1, 2, 3], [3, 2, 1]))         # Dovrebbe restituire True
print(reverse([1, 2, 3], [1, 2, 3]))         # Dovrebbe restituire False
print(reverse([], []))                        # Dovrebbe restituire True (liste vuote)
print(reverse([1], [1]))                      # Dovrebbe restituire True
print(reverse([1, 2], [1]))                   # Dovrebbe restituire False (lunghezze diverse)
print(reverse(['a', 'b'], ['b', 'a']))       # Dovrebbe restituire True
print(reverse([1, 2, 2], [2, 2, 1]))         # Dovrebbe restituire True


True
False
True
True
False
True
True


### 9. Scrivi una funzione che restituisce il valore massimo per una chiave da una lista di dizionari.

In [118]:
def max_value(lst:list,key:str) -> int:
    if len(lst) == 0:
        return None

    found = False
    max_val = None

    for dictionary in lst:
        if key in dictionary:
            if not found:
                max_val = dictionary[key]
                found = True
            elif dictionary[key] > max_val:
                max_val = dictionary[key]

    return max_val

# Test con vari casi
test_dict1 = [{'prezzo': 10, 'quantità': 5},
              {'prezzo': 20, 'quantità': 3},
              {'prezzo': 15, 'quantità': 4}]

test_dict2 = [{'voto': -2, 'peso': 1},
              {'voto': -5, 'peso': 2},
              {'voto': -1, 'peso': 3}]

test_dict3 = []  # lista vuota

test_dict4 = [{'nome': 'Mario', 'età': 30},
              {'nome': 'Luigi', 'età': 25},
              {'nome': 'Peach', 'età': 28}]

# Test dei casi
print(max_value(test_dict1, 'prezzo'))    # Dovrebbe restituire 20
print(max_value(test_dict2, 'voto'))      # Dovrebbe restituire -1 (massimo tra negativi)
print(max_value(test_dict3, 'chiave'))    # Dovrebbe gestire la lista vuota
print(max_value(test_dict4, 'età'))       # Dovrebbe restituire 30
print(max_value(test_dict1, 'inesistente'))  # Dovrebbe gestire chiave non presente


20
-1
None
30
None


### 10. Scrivi una funzione che prende una lista di tuple e restituisce la somma dei secondi elementi.

In [119]:
def sumtuples (lst:list) -> int:
    if len(lst) == 0:
        return None
    somma = 0
    for tupla in lst:
        somma += tupla[1]

    return somma

# Test con vari casi
test1 = [(1, 2), (3, 4), (5, 6)]           # Dovrebbe restituire 12 (2 + 4 + 6)
test2 = [('a', 1), ('b', 2), ('c', 3)]     # Dovrebbe restituire 6 (1 + 2 + 3)
test3 = [(0, -1), (0, -2), (0, -3)]        # Dovrebbe restituire -6 (-1 + -2 + -3)
test4 = []                                  # Dovrebbe restituire None (lista vuota)
test5 = [(1, 0)]                           # Dovrebbe restituire 0

print(sumtuples(test1))  # 12
print(sumtuples(test2))  # 6
print(sumtuples(test3))  # -6
print(sumtuples(test4))  # None
print(sumtuples(test5))  # 0


12
6
-6
None
0


### 11. Crea una classe Person con nome e eta, e un metodo che stampa un saluto.

In [120]:
class Person:
    def __init__(self,nome,eta):
        self.nome = nome
        self.eta = eta
    def __repr__(self):
        return print(f'Ciao! Il tuo nome è:{self.nome} e la tua età è:{self.eta}')

# Test con vari casi
persona1 = Person("Mario", 25)
persona2 = Person("Anna", 30)
persona3 = Person("", 0)       # Test con valori vuoti/zero
persona4 = Person("Luigi", 17) # Test con un minorenne

persona1.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Mario e la tua età è:25
persona2.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Anna e la tua età è:30
persona3.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è: e la tua età è:0
persona4.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Luigi e la tua età è:17


Ciao! Il tuo nome è:Mario e la tua età è:25
Ciao! Il tuo nome è:Anna e la tua età è:30
Ciao! Il tuo nome è: e la tua età è:0
Ciao! Il tuo nome è:Luigi e la tua età è:17


### 12. Crea una classe BankAccount con saldo, deposito e prelievo.

In [121]:
class BankAccount:
    def __init__(self,saldo):
        self.saldo = saldo

    def deposito(self,deposito):
        if deposito < 0:
            return False
        self.saldo += deposito
        return True

    def prelievo(self,prelievo):
        if prelievo > self.saldo or prelievo < 0:
            return False
        self.saldo = self.saldo - prelievo
        return True

# Test con vari casi
conto = BankAccount(1000)
print(conto.deposito(500))      # True (deposito riuscito)
print(conto.saldo)              # 1500
print(conto.deposito(-100))     # False (importo negativo)
print(conto.saldo)              # 1500 (saldo non modificato)
print(conto.prelievo(2000))     # False (saldo insufficiente)
print(conto.saldo)              # 1500 (saldo non modificato)
print(conto.prelievo(500))      # True (prelievo riuscito)
print(conto.saldo)              # 1000

True
1500
False
1500
False
1500
True
1000


### 13. Override del metodo __str__ in una classe Car.

In [122]:
class Car:
    def __init__(self,nome,marca,modello):
        self.nome = nome
        self.marca = marca
        self.modello = modello
    def __str__(self):
        return f'La macchina è:{self.nome}\n La marca è:{self.marca}\n Il modello è: {self.modello} '


# Test con vari casi
auto1 = Car("500", "Fiat", "Sport")
auto2 = Car("Model S", "Tesla", "Long Range")
auto3 = Car("Urus", "Lamborghini", "S")

# Test stampa diretta
print(auto1)  # Dovrebbe mostrare: La macchina è:500 La marca è:Fiat Il modello è: Sport
print(auto2)  # Dovrebbe mostrare: La macchina è:Model S La marca è:Tesla Il modello è: Long Range
print(auto3)  # Dovrebbe mostrare: La macchina è:Urus La marca è:Lamborghini Il modello è: S

# Test conversione esplicita a stringa
stringa_auto = str(auto1)
print(stringa_auto)  # Dovrebbe mostrare lo stesso output di print(auto1)


La macchina è:500
 La marca è:Fiat
 Il modello è: Sport 
La macchina è:Model S
 La marca è:Tesla
 Il modello è: Long Range 
La macchina è:Urus
 La marca è:Lamborghini
 Il modello è: S 
La macchina è:500
 La marca è:Fiat
 Il modello è: Sport 


### 14. Crea una classe Rectangle con metodi per area e perimetro.

In [123]:
class Rectangle:
    def __init__(self,base,altezza):
        self.base = base
        self.altezza = altezza
    def area(self):
        return self.base * self.altezza
    def perimetro(self):
        return (self.base*2)+(self.altezza*2)

# Test con vari casi
rettangolo1 = Rectangle(5, 3)      # rettangolo 5x3
rettangolo2 = Rectangle(10, 10)    # quadrato 10x10
rettangolo3 = Rectangle(2.5, 4)    # rettangolo con decimali
rettangolo4 = Rectangle(0, 5)      # rettangolo con base zero

# Test calcolo area
print(rettangolo1.area())      # Dovrebbe stampare 15 (5 * 3)
print(rettangolo2.area())      # Dovrebbe stampare 100 (10 * 10)
print(rettangolo3.area())      # Dovrebbe stampare 10.0 (2.5 * 4)
print(rettangolo4.area())      # Dovrebbe stampare 0 (0 * 5)

# Test calcolo perimetro
print(rettangolo1.perimetro())  # Dovrebbe stampare 16 ((5 * 2) + (3 * 2))
print(rettangolo2.perimetro())  # Dovrebbe stampare 40 ((10 * 2) + (10 * 2))
print(rettangolo3.perimetro())  # Dovrebbe stampare 13.0 ((2.5 * 2) + (4 * 2))
print(rettangolo4.perimetro())  # Dovrebbe stampare 10 ((0 * 2) + (5 * 2))


15
100
10.0
0
16
40
13.0
10


### 15. Crea una classe Student con lista voti e media.

In [124]:
class Student:
    def __init__(self, nome, voti):
        self.nome = nome
        self.voti = voti

    def media(self):
        if len(self.voti) == 0:
            return 0
        return sum(self.voti) / len(self.voti)  # Usa la funzione built-in sum

# Test con vari casi
studente1 = Student("Mario", [18, 25, 30, 28])
studente2 = Student("Luigi", [30, 30, 30])
studente3 = Student("Anna", [])
studente4 = Student("Luca", [18, 18, 18, 18])
studente5 = Student("Elena", [25, 28, 27, 26])

# Test stampa voti
print(f"{studente1.nome}: voti = {studente1.voti}")
print(f"{studente2.nome}: voti = {studente2.voti}")
print(f"{studente3.nome}: voti = {studente3.voti}")

# Test calcolo media
print(f"La media di {studente1.nome} è: {studente1.media()}")  # Dovrebbe essere circa 25.25
print(f"La media di {studente2.nome} è: {studente2.media()}")  # Dovrebbe essere 30.0
print(f"La media di {studente3.nome} è: {studente3.media()}")  # Dovrebbe essere 0
print(f"La media di {studente4.nome} è: {studente4.media()}")  # Dovrebbe essere 18.0
print(f"La media di {studente5.nome} è: {studente5.media()}")  # Dovrebbe essere 26.5

Mario: voti = [18, 25, 30, 28]
Luigi: voti = [30, 30, 30]
Anna: voti = []
La media di Mario è: 25.25
La media di Luigi è: 30.0
La media di Anna è: 0
La media di Luca è: 18.0
La media di Elena è: 26.5


### 16. Crea una classe Animal e una sottoclasse Dog che override speak().

In [125]:
class Animal:
    def __init__(self,nome):
        self.nome = nome
    def speak(self):
        return "L'animale fa un verso"
class Dog(Animal):
    def __init__(self,nome):
        super().__init__(nome)
    def speak(self):
        return 'Il cane abbaia'

# Test con vari casi
animale = Animal("generico")
cane = Dog("Fido")

# Test del metodo speak() per entrambe le classi
print(animale.speak())    # Dovrebbe stampare "L'animale fa un verso"
print(cane.speak())       # Dovrebbe stampare "Il cane abbaia"

# Test con nome
print(animale.nome)       # Dovrebbe stampare "generico"
print(cane.nome)         # Dovrebbe stampare "Fido"

# Test con diversi cani
cane2 = Dog("Rex")
print(cane2.speak())      # Dovrebbe stampare "Il cane abbaia"
print(cane2.nome)        # Dovrebbe stampare "Rex"



L'animale fa un verso
Il cane abbaia
generico
Fido
Il cane abbaia
Rex


### 17. Due oggetti Book sono uguali se titolo e autore coincidono.

In [126]:
class Book:
    def __init__(self,nome,autore):
        self.nome = nome
        self.autore = autore
    def __eq__(self, other):
        if type(self) == type(other):
            return (self.nome == other.nome) and (self.autore == other.autore)
        else:
            return False

# Test con vari casi
libro1 = Book("Il Signore degli Anelli", "Tolkien")
libro2 = Book("Il Signore degli Anelli", "Tolkien")  # Stesso libro
libro3 = Book("Il Signore degli Anelli", "Smith")    # Stesso titolo, autore diverso
libro4 = Book("Harry Potter", "Rowling")             # Libro completamente diverso
altro_oggetto = "Non un libro"                       # Test con tipo diverso

# Test di uguaglianza
print(libro1 == libro2)  # Dovrebbe stampare True
print(libro1 == libro3)  # Dovrebbe stampare False
print(libro1 == libro4)  # Dovrebbe stampare False
print(libro1 == altro_oggetto)  # Dovrebbe stampare False

# Test con attributi
print(libro1.nome)    # Dovrebbe stampare "Il Signore degli Anelli"
print(libro1.autore)  # Dovrebbe stampare "Tolkien"



True
False
False
False
Il Signore degli Anelli
Tolkien


### 18. Crea una Shape astratta con area(), da implementare in Circle e Square.

In [127]:
# 1. Importa ABC e abstractmethod dal modulo abc
from abc import ABC, abstractmethod

# 2. Crea la classe astratta ereditando da ABC
class Shape(ABC):

    def __init__(self, nome):
        self.nome = nome

    # 3. Dichiara i metodi astratti con il decoratore
    @abstractmethod
    def calcola_area(self):
        """Metodo astratto per calcolare l'area."""
        pass # Non c'è bisogno di codice qui

class Quadrato(Shape):

    def __init__(self, lato):
        super().__init__("Quadrato") # Chiama il costruttore della classe padre
        self.lato = lato

    # Implementazione OBBLIGATORIA del metodo astratto
    def calcola_area(self):
        return self.lato ** 2
class Cerchio(Shape):

    def __init__(self,raggio):
        super().__init__('Cerchio')
        self.raggio = raggio
    def calcola_area(self):
        return 2*3.14*(self.raggio**2)

# Test
quadrato = Quadrato(5)
cerchio = Cerchio(3)

print(quadrato.calcola_area())   # Dovrebbe stampare 25
print(cerchio.calcola_area())    # Dovrebbe stampare 56.52


25
56.52


### 19. Crea una classe Counter che incrementa solo se il valore e pari.

In [128]:
class Counter:
    def __init__(self,count):
        self.count = count
    def counter(self,number):
        if number % 2 == 0:
            self.count += number

# Test con vari casi
contatore = Counter(0)

# Incremento con numero pari
contatore.counter(2)  # Dovrebbe incrementare il contatore a 2
print(contatore.count)  # Dovrebbe stampare 2

# Incremento con numero dispari
contatore.counter(3)  # Non dovrebbe cambiare il contatore
print(contatore.count)  # Dovrebbe stampare 2

# Incremento con numero pari negativo
contatore.counter(-4)  # Dovrebbe decrementare il contatore a -2
print(contatore.count)  # Dovrebbe stampare -2

# Incremento con zero
contatore.counter(0)  # Non dovrebbe cambiare il contatore
print(contatore.count)  # Dovrebbe stampare -2

2
2
-2
-2


### 20. Crea una classe Timer con start, stop e elapsed.

In [129]:
class Timer:
    def __init__(self,start,stop):
        self.start = start
        self.stop = stop
        self.elapsed = stop - start
# Test con vari casi
timer1 = Timer(0, 10)  # Timer con start 0 e stop 10
print(timer1.elapsed)  # Dovrebbe stampare 10

timer2 = Timer(5, 20)  # Timer con start 5 e stop 20
print(timer2.elapsed)  # Dovrebbe stampare 15

timer3 = Timer(10, 10)  # Timer con start e stop uguali
print(timer3.elapsed)  # Dovrebbe stampare 0

timer4 = Timer(15, 5)  # Timer con start maggiore di stop
print(timer4.elapsed)  # Dovrebbe stampare -10

10
15
0
-10


### 21. Usa lambda per ordinare tuple in base al secondo elemento.

In [130]:
# Lista di tuple (es. prodotto, quantità)
lista_tuple = [('Mela', 50), ('Banana', 25), ('Arancia', 100), ('Kiwi', 10)]

lista_ordinata = sorted(lista_tuple,key= lambda x: x[1])

print(lista_ordinata)


[('Kiwi', 10), ('Banana', 25), ('Mela', 50), ('Arancia', 100)]


### 22. Usa filter per tenere solo numeri > 100.

In [131]:
numeri_da_filtrare = [25, 158, 99, 100, 101, -10, 500, 0, 100.5]

numeri_filtrati = list(filter(lambda x: x>100,numeri_da_filtrare))

print(numeri_filtrati)


[158, 101, 500, 100.5]


### 23. Usa map per convertire stringhe in uppercase.

In [132]:
parole_da_trasformare = ["ciao", "Mondo", "PYTHON", "Test con Numeri 123", "", "a"]

parole_trasformate = list(map(lambda s: s.upper(),parole_da_trasformare))
print(parole_trasformate)


['CIAO', 'MONDO', 'PYTHON', 'TEST CON NUMERI 123', '', 'A']


### 24. Usa reduce per calcolare il prodotto degli elementi.

In [133]:
from functools import reduce
numeri_da_moltiplicare = [2, 3, 5, -4, 1]

prodotto = reduce(lambda x, y: x * y, numeri_da_moltiplicare)
print(prodotto)

-120


### 25. Scrivi una lambda che restituisce il maggiore tra due numeri.

In [134]:
coppie_di_test = [
    (10, 5),
    (3, 8),
    (7, 7),
    (4, -2),
    (-5, -10),
    (0, 9)
]

trova_maggiore = lambda x, y: x if x > y else y

# 2. Itera attraverso le coppie di test.
for coppia in coppie_di_test:
    # 3. 'spacchetta' la tupla in due variabili separate per chiarezza.
    num1, num2 = coppia

    # 4. CHIAMA la funzione con i due numeri e salva il risultato.
    risultato = trova_maggiore(num1, num2)

    # 5. Stampa il RISULTATO, non la funzione.
    print(f"Tra {num1} e {num2}, il maggiore è: {risultato}")


Tra 10 e 5, il maggiore è: 10
Tra 3 e 8, il maggiore è: 8
Tra 7 e 7, il maggiore è: 7
Tra 4 e -2, il maggiore è: 4
Tra -5 e -10, il maggiore è: -5
Tra 0 e 9, il maggiore è: 9


### 26. Crea un array 3x3 di zeri.

In [135]:
array = np.zeros((3,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 27. Genera un array 4x4 con numeri casuali tra 0 e 1.

In [136]:
from numpy.random._examples.cffi.extending import rng

# Genera un singolo float
random_float = rng.random()
random_array = rng.random(16)
print(f"Array di 5 float casuali:\n{random_array}")

random_matrix = rng.random(size=(4, 4))
print(f"Matrice 2x3 di float casuali:\n{random_matrix}")

Array di 5 float casuali:
[0.57819389 0.22387711 0.50229694 0.2409432  0.83883832 0.4303899
 0.39819893 0.72968125 0.54372486 0.91124739 0.9336814  0.57136715
 0.35532578 0.46315922 0.58618549 0.29349501]
Matrice 2x3 di float casuali:
[[3.51296785e-01 5.41631918e-01 3.09553997e-01 4.70715017e-04]
 [1.63479916e-01 7.20584643e-01 9.74411056e-01 5.72825395e-03]
 [3.69204588e-01 6.11678672e-01 4.80811639e-01 5.16196688e-01]
 [8.23409608e-02 4.96103165e-01 2.56272657e-02 4.21010752e-01]]


### 28. Crea array da 1 a 20, sostituisci multipli di 4 con -1.

In [137]:
array = np.arange(1,21)
print(array)
mask = array %4 == 0
print(mask)
array[mask] = -1
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False False False  True False False False  True False False False  True
 False False False  True False False False  True]
[ 1  2  3 -1  5  6  7 -1  9 10 11 -1 13 14 15 -1 17 18 19 -1]


### 29. Calcola la media di ogni colonna di un array 5x5.

In [138]:
array = np.random.randint(0,100,(5,5))
print(array)
media =  np.mean(array,axis = 0) # Colonna  = 0, Riga = 1
print(media)


[[ 9 16 30 56 20]
 [69 79 23 19 65]
 [84 76 39 23 79]
 [99 61 94 29 24]
 [29 84 32 53 68]]
[58.  63.2 43.6 36.  51.2]


### 30. Conta i valori > 10 in un array 10x10 casuale.

In [139]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array > 10).sum()

print(count)

[[26 11 40 37 30 53 16 86 41 67]
 [10 38 98 26 67  3 73 47 92 40]
 [79  2 31 54 75 27  8 96  8 18]
 [12 86 11 54 49 66 77 72 26 67]
 [ 9 86 25 84 34 60 88 37 49 73]
 [ 5  2 59 42 83 25 47  8  6 64]
 [66 48 21 94 99 63 64  5  6 40]
 [89  4 95  0 94 97 99 30 18 56]
 [86 42  2 41 10 75 10 75 30 98]
 [75 52 97 40 53 14 29  4 93 56]]
82


### 31. Conta valori dispari negativi in un array.

In [140]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array % 2 != 0).sum()

print(count)


[[56 28 71 67 34  5 99 30 97 34]
 [81 61 11 17 86 78 38 12 94 82]
 [24 62 62 68 37  6 10 39 55 58]
 [ 2  6  9 53 11 56 79 70 86 96]
 [23 16 29 57 76 29 33 86 25 80]
 [50 97 10 75 66  7 59 78 58 47]
 [66  0 63 74 78 33 90 75 75 83]
 [24 57 55 61 75 90 59 21 60 32]
 [99 42  6 50 70 64 13 18 28 77]
 [90 80 46 92 26 70  8  0 58 89]]
42


### 32. Restituisci array booleano per i multipli di 7.

In [141]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array % 7 != 0).sum()

print(count)


[[64 83 95 10 45 24 18 94  6  4]
 [40 19 12 82 15 34 74 89 94 34]
 [22 54 18 55 85 96 77 96 76 32]
 [25 42 55 26  3 28 82 41 39 20]
 [17 84 18  6 14 32 56 22  5  0]
 [84 68 68 78 62 99 25 42 26  6]
 [44 79 91 76 73 81 37 56 75 17]
 [11 95 11  5  3  6 67 40 26 47]
 [87 23 85 72 79  8  3 93 80 63]
 [68 55 18 98 25 94 72 18 53 43]]
87


### 33. Normalizza un array (media 0, std 1).

In [142]:
array = np.random.randint(0,100,(10,10))
print('Array pre Standardizzazione: \n')
print(array)
print('\n')
media = array.mean()
# Potresti anche usare np.mean(punteggi)

# 3. Calcoliamo la deviazione standard (σ)
dev_std = array.std()

array = array - media / dev_std
print('Array Post Standardizzazione: \n')
print(array)



Array pre Standardizzazione: 

[[41  4 42 74 70  2 39 94 97 29]
 [65 76 28 41 15 18 23 32 87 62]
 [20 38 11 56 15 66  6 39 48 10]
 [31 64 93 30 17 43 63 37 76  2]
 [ 1 85 40 41 34 90 16 41 55 79]
 [44 15 24 93 17 34 66 88  6 27]
 [47 17 16 80 57 61 21 91 58 65]
 [60  0 18 48 92  8 60 73 27 47]
 [95 39 85 21 90 61 86 34 34 27]
 [91 12 11 37 43 77 66 52 10 95]]


Array Post Standardizzazione: 

[[39.36219526  2.36219526 40.36219526 72.36219526 68.36219526  0.36219526
  37.36219526 92.36219526 95.36219526 27.36219526]
 [63.36219526 74.36219526 26.36219526 39.36219526 13.36219526 16.36219526
  21.36219526 30.36219526 85.36219526 60.36219526]
 [18.36219526 36.36219526  9.36219526 54.36219526 13.36219526 64.36219526
   4.36219526 37.36219526 46.36219526  8.36219526]
 [29.36219526 62.36219526 91.36219526 28.36219526 15.36219526 41.36219526
  61.36219526 35.36219526 74.36219526  0.36219526]
 [-0.63780474 83.36219526 38.36219526 39.36219526 32.36219526 88.36219526
  14.36219526 39.36219526 53.3

### 34. Da una lista di array, restituisci quello con std maggiore.

### 35. Restituisci il valore piu frequente in un array.

In [143]:
# La tua soluzione qui...


### 36. Divisione sicura tra due numeri con gestione divisione per zero.

In [144]:
# La tua soluzione qui...


### 37. Accetta solo liste, stampa errore altrimenti.

In [145]:
# La tua soluzione qui...


### 38. Accetta solo array Numpy, restituisce massimo o errore.

In [146]:
# La tua soluzione qui...


### 39. Somma due liste elemento per elemento, gestendo lunghezze diverse.

In [147]:
# La tua soluzione qui...


### 40. Apre un file e gestisce l'errore se il file non esiste.

In [148]:
# La tua soluzione qui...


### 41. Verifica se una stringa e palindroma.

In [149]:
# La tua soluzione qui...


### 42. Simula due dadi e ritorna la somma.

In [150]:
# La tua soluzione qui...


### 43. Inverti chiavi e valori di un dizionario.

In [151]:
# La tua soluzione qui...


### 44. Restituisci la sottolista con somma massima.

In [152]:
# La tua soluzione qui...


### 45. Controlla se due stringhe sono anagrammi.

In [153]:
# La tua soluzione qui...


### 46. Ordina i valori unici di un array 1D.

In [154]:
# La tua soluzione qui...


### 47. Restituisci la diagonale principale di una matrice NxN.

In [155]:
# La tua soluzione qui...


### 48. Restituisci il secondo valore massimo in un array.

In [156]:
# La tua soluzione qui...


### 49. Differenze tra elementi consecutivi in un array.

In [157]:
# La tua soluzione qui...


### 50. Costruisci un array NxN con 1 sulla diagonale e 0 altrove.

In [158]:
# La tua soluzione qui...
