#Python Language Advanced

##30/10/2024

- vector sum
    - function
    - objects

In [ ]:
v_1 =       [0,  12,  32, -2, 6]
v_2 =       [90, -3, 38, 12, -19]
#v_sum =    [90, 9, 70, 10, -13]

In [ ]:
v_1 + v_2

[0, 12, 32, -2, 6, 90, -3, 38, 12, -19]

In [ ]:
#write a function that takes two lists of numbers in input and returns their vector sum
def vector_sum(v_1, v_2):
    res_list = []
    if len(v_1) == len(v_2):
        for i in range(len(v_2)):
            sum_elements = v_1[i] + v_2[i]
            res_list.append(sum_elements)
    return res_list


In [ ]:
vector_sum(v_1, v_2)

[90, 9, 70, 10, -13]

In [ ]:
class Vector:
    def __init__(self, list_of_numbers):
        self.list_of_numbers = list_of_numbers

    def __repr__(self):
        return str(self.list_of_numbers)

    def __add__(self, other):
        return Vector(vector_sum(self.list_of_numbers, other.list_of_numbers))

In [ ]:
vec_1 = Vector(v_1)
vec_2 = Vector(v_2)
vec_1 + vec_2

[90, 9, 70, 10, -13]

##Numpy Basics

In [ ]:
import numpy as np

In [ ]:
vector_1 = np.array(v_1)
vector_2 = np.array(v_2)
vector_1

array([ 0, 12, 32, -2,  6])

In [ ]:
vector_1 + vector_2

array([ 90,   9,  70,  10, -13])

In [ ]:
vector_1 * vector_2

array([   0,  -36, 1216,  -24, -114])

In [ ]:
vector_1 * vector_2.T

array([   0,  -36, 1216,  -24, -114])

In [ ]:
a_matrix_of_numbers = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [ ]:
m_1 = np.array(a_matrix_of_numbers)
m_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m_1 + m_1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
m_1 * m_1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
m_1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
m_1.T * m_1

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [ ]:
m_1 * m_1.T

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
m_1.dot(m_1.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [ ]:
m_1.T.dot(m_1)

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [ ]:
m_1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
m_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m_1 * m_1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
s_1 = np.array(8)
s_1

array(8)

In [ ]:
m_1 * s_1

array([[ 8, 16, 24, 32],
       [40, 48, 56, 64],
       [72, 80, 88, 96]])

In [ ]:
vector_1.shape

(5,)

In [ ]:
s_1.shape

()

In [ ]:
m_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m_1.max()

12

In [ ]:
m_1.mean()

6.5

In [ ]:
m_1.diagonal()

array([ 1,  6, 11])

- import numpy
- arrays
    - vectors and arrays
    - arithmetic operators
    - mean, sum, max, min, etc.
    - transpose

In [ ]:
v_1[0]

0

In [ ]:
vector_1[0:4]

array([ 0, 12, 32, -2])

In [ ]:
vector_1

array([ 0, 12, 32, -2,  6])

In [ ]:
#boolean mask
vector_1[[False, False, False, True, False]]

array([-2])

In [ ]:
vector_1 * 3
vector_1 + 3
vector_1 < 3

array([ True, False, False,  True, False])

In [ ]:
array_of_ages = np.array([41, 24, 12, 23, 92, 34, 54, 73])
ages_above_70 = array_of_ages >= 70

In [ ]:
array_of_ages[ages_above_70]

array([92, 73])

In [ ]:
ages_above_18 = array_of_ages >= 18
array_of_ages[ages_above_18]

array([41, 24, 23, 92, 34, 54, 73])

In [ ]:
#find the ages of the people possibly working with boolean masks
# >= 16
# < 70
older_than_16_mask = array_of_ages >= 16
older_than_16_array = array_of_ages[older_than_16_mask]
younger_than_70_mask = older_than_16_array < 70
people_possibly_working_array = older_than_16_array[younger_than_70_mask]
people_possibly_working_array

array([41, 24, 23, 34, 54])

In [ ]:
older_than_16_mask = array_of_ages >= 16
younger_than_70_mask = array_of_ages < 70
people_that_work_mask = older_than_16_mask & younger_than_70_mask
array_of_ages[people_that_work_mask]
# ||

array([41, 24, 23, 34, 54])

- boolean masks
    - element access (index, booleans)
    - comparison operators
    - combining boolean masks




In [ ]:
list(range(0, 1, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(6, 18)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
np.arange(1, 0, -0.1) > 0.3

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [ ]:
vector_3 = np.arange(16)
vector_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
vector_3.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.randint(0,12)

9

In [ ]:
np.random.randint(-1000,1000,100).reshape(10,10)

array([[-378, -834, -388,   65,  292,  -74, -395, -622,  275, -480],
       [ 615,  385,  -28,  638,  188,  176, -350,   26, -350,    6],
       [ 870, -212,  312,  140, -206, -850,  624, -308,   75,  565],
       [-620,  989,  277,  911,   57,  547,  638,  376, -555, -774],
       [-476, -409, -973,  944,  693,  855,  841, -884,  -67, -698],
       [-396, -781,  241, -562,  863, -971, -938,  -22, -931,  631],
       [ 240, -372, -459,   76, -108,  603,  -73, -713,  822,  981],
       [ 482, -430,  804, -376,  638, -964, -777,  518,  378,  311],
       [ 968, -125,  251, -984,  412,  544, -900, -743, -862, -624],
       [-247,  925, -365, -807,  -29, -747, -644, -752, -567,   43]])

In [ ]:
array_of_zeroes = np.zeros((4,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
new_array_of_zeros = array_of_zeroes
new_array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
new_array_of_zeros[0][0] = 1
new_array_of_zeros

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array_of_zeroes

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
new_array_of_zeros = np.copy(array_of_zeroes)

In [ ]:
new_array_of_zeros

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
new_array_of_zeros[0][1] = 1
new_array_of_zeros

array([[1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array_of_zeroes

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- advanced arrays
    - arange
    - reshape vector into array
    - ones, zeros, identity
    - random.randint
    - np.copy

**Exercise:** transform random_array into an array of numbers between 0 and 1

#Basic Exercises

Ex: Write a function that returns True if all the elements in the input list are even

In [ ]:
#done

**Ex: Write a function that returns the maximum value in a list**

In [ ]:
def find_maximum(list_of_numbers):
    maximum = list_of_numbers[0]
    for number in list_of_numbers:
        if number > maximum:
            maximum = number

    return maximum

In [ ]:
find_maximum([0,-2, 30, -45, 90])

90

In [ ]:
def find_maximum(list_of_numbers):
    sorted_list = sorted(list_of_numbers)
    return sorted_list[-1]

In [ ]:
find_maximum([0,-2, 30, -45, 90])

90

In [ ]:
def find_maximum(list_of_numbers):
    maximum = 0
    for number in list_of_numbers:
        if number > maximum:
            maximum = number

    return maximum

In [ ]:
find_maximum([-20,-2, -30, -45, -90])

0

In [ ]:
def find_maximum(list_of_numbers):
    return max(list_of_numbers)


In [ ]:
find_maximum([-20,-2, -30, -45, -90])

-2

In [ ]:
find_maximum = lambda x : max(x)

In [ ]:
find_maximum([-20,-2, -30, -45, -90])

-2

Ex: Write a function that returns the sum of all values in the list

1. Write a function that returns True if all the elements in the input list are even
2. Write a function that returns the maximum value in a list
2. Write a function that returns the sum of all values in the list
2. Write a function that accepts a list of numbers as input and returns an inverted version of the list
2. Write a function that returns the first and last elements of a list
3. Write a function that, given a, b, c, x as inputs, calculates ax^2 + bx + c
4. Write a function that calculates the number of days between two dates. The dates can be tuples
5. Write a function that accepts 2 dictionaries as input and returns a single dictionary with the same data (merged)
6. Write a function to print the content of a dictionary in order by key
7. Write a function to find all keys in the provided dictionary that have the given value
8. Write a function to sort a tuple by its float element

Ex: Write a function to print the content of a dictionary in order by *key*