# 💻 Esercitazione I

In [6]:
import numpy as np


### 1. Scrivi una funzione che prende una lista di interi e restituisce un dizionario con chiavi 'pari' e 'dispari'.

In [2]:

def fun(a:list) -> dict:
    dict_pd = {'pari': 0,
            'dispari': 0}
    for number in a:
        if number %2 == 0:
            dict_pd['pari'] += 1
        else:
            dict_pd['dispari'] +=1
    return dict_pd

# Test con vari casi
test1 = [1, 2, 3, 4, 5]  # 2 pari, 3 dispari
test2 = [2, 4, 6, 8]     # tutti pari
test3 = [1, 3, 5, 7]     # tutti dispari
test4 = []               # lista vuota

print("Test 1:", fun(test1))  # Dovrebbe dare {'pari': 2, 'dispari': 3}
print("Test 2:", fun(test2))  # Dovrebbe dare {'pari': 4, 'dispari': 0}
print("Test 3:", fun(test3))  # Dovrebbe dare {'pari': 0, 'dispari': 4}
print("Test 4:", fun(test4))  # Dovrebbe dare {'pari': 0, 'dispari': 0}


Test 1: {'pari': 2, 'dispari': 3}
Test 2: {'pari': 4, 'dispari': 0}
Test 3: {'pari': 0, 'dispari': 4}
Test 4: {'pari': 0, 'dispari': 0}


### 2. Scrivi una funzione che conta quante volte ogni carattere appare in una stringa.

In [3]:
def conta_carattere(s:str,c:str) -> int:
    count = 0
    for character in s:
        if character == c:
            count += 1
    return  count

# Test con vari casi
print(conta_carattere("hello", "l"))      # Dovrebbe dare 2
print(conta_carattere("python", "p"))     # Dovrebbe dare 1
print(conta_carattere("banana", "a"))     # Dovrebbe dare 3
print(conta_carattere("test", "x"))       # Dovrebbe dare 0
print(conta_carattere("", "a"))           # Dovrebbe dare 0
print(conta_carattere("AAA", "A"))        # Dovrebbe dare 3
print(conta_carattere("ciao mondo", " ")) # Dovrebbe dare 1

2
1
3
0
0
3
1


### 3. Scrivi una funzione che riceve una lista e restituisce True se tutti gli elementi sono diversi.

In [4]:
def div(lst:list) -> bool:
    num_prec = 0
    for num in lst:
        if num == num_prec:
            return False
        else:
            num_prec = num

    return True

# Test con vari casi
print(div([1, 2, 3, 4, 5]))  # Dovrebbe restituire True (tutti diversi)
print(div([1, 1, 2, 3, 4]))  # Dovrebbe restituire False (ci sono duplicati)
print(div([]))               # Dovrebbe restituire True (lista vuota)
print(div([7]))              # Dovrebbe restituire True (un solo elemento)
print(div([1, 2, 3, 3, 4]))  # Dovrebbe restituire False (duplicati consecutivi)

True
False
True
True
False


### 4. Scrivi una funzione che restituisce una lista con elementi unici, mantenendo l'ordine.

In [5]:
def elem_unic(lst:list) -> list:

    lst = set(lst)
    lst = list(lst)
    return lst

# Test con vari casi
print(elem_unic([1, 2, 2, 3, 4, 4, 5]))  # Dovrebbe restituire [1, 2, 3, 4, 5]
print(elem_unic([7, 7, 7, 7]))           # Dovrebbe restituire [7]
print(elem_unic([]))                    # Dovrebbe restituire []
print(elem_unic([1, 2, 3, 4, 5]))       # Dovrebbe restituire [1, 2, 3, 4, 5]
print(elem_unic([5, 4, 3, 2, 1, 1, 2])) # Dovrebbe restituire [5, 4, 3, 2, 1]

[1, 2, 3, 4, 5]
[7]
[]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


### 5. Scrivi una funzione one-liner che restituisce tutti i multipli di 5 in una lista.

In [6]:
def multiply_of_5(lst:list) -> list:
    return [number for number in lst if number %5 == 0]

# Test con vari casi
print(multiply_of_5([5, 10, 15, 20]))       # Dovrebbe restituire [5, 10, 15, 20]
print(multiply_of_5([1, 2, 3, 4]))          # Dovrebbe restituire []
print(multiply_of_5([0, 5, 25, 30, 7]))     # Dovrebbe restituire [0, 5, 25, 30]
print(multiply_of_5([-5, -10, 0, 3, 8]))    # Dovrebbe restituire [-5, -10, 0]
print(multiply_of_5([]))                    # Dovrebbe restituire []


[5, 10, 15, 20]
[]
[0, 5, 25, 30]
[-5, -10, 0]
[]


### 6. Scrivi una funzione che restituisce una lista dei quadrati dei numeri positivi.

In [7]:
def quadrati(lst:list) -> list:
    return [number **2 for number in lst if number > 0 ]

# Test con vari casi
print(quadrati([1, 2, 3, 4]))         # Dovrebbe restituire [1, 4, 9, 16]
print(quadrati([-1, 2, -3, 4]))       # Dovrebbe restituire [4, 16]
print(quadrati([-2, -1, 0]))          # Dovrebbe restituire []
print(quadrati([]))                   # Dovrebbe restituire []
print(quadrati([5, -5, 10, -10, 3]))  # Dovrebbe restituire [25, 100, 9]

[1, 4, 9, 16]
[4, 16]
[]
[]
[25, 100, 9]


### 7. Scrivi una funzione che restituisce il massimo numero di True consecutivi in una lista di booleani.

In [8]:
def max_num(lst:list) -> int:
      if len(lst) == 0:
          return 0
      count = 0
      max  = 0
      for i in range (0,len(lst)):
        if lst[i] == True:
            count +=1
            if count > max:
                max = count
        else:
            count = 0
      return max

# Test con vari casi
print(max_num([True, True, False, True]))          # Dovrebbe restituire 2
print(max_num([True, True, True, False]))          # Dovrebbe restituire 3
print(max_num([False, False, True, True]))         # Dovrebbe restituire 2
print(max_num([True]))                             # Dovrebbe restituire 1
print(max_num([False, True, False, True, True]))   # Dovrebbe restituire 2
print(max_num([False, False, False]))              # Dovrebbe restituire 0


2
3
2
1
2
0


### 8. Scrivi una funzione che prende due liste e restituisce True se una e la reversa dell'altra.

In [9]:
def reverse(lst1:list,lst2:list) -> bool:
    if len(lst1) != len(lst2):
        return False
    for i in range (0,len(lst1)):
        if lst1[i] != lst2[-1-i]:
            return False
    return True

# Test con vari casi
print(reverse([1, 2, 3], [3, 2, 1]))         # Dovrebbe restituire True
print(reverse([1, 2, 3], [1, 2, 3]))         # Dovrebbe restituire False
print(reverse([], []))                        # Dovrebbe restituire True (liste vuote)
print(reverse([1], [1]))                      # Dovrebbe restituire True
print(reverse([1, 2], [1]))                   # Dovrebbe restituire False (lunghezze diverse)
print(reverse(['a', 'b'], ['b', 'a']))       # Dovrebbe restituire True
print(reverse([1, 2, 2], [2, 2, 1]))         # Dovrebbe restituire True


True
False
True
True
False
True
True


### 9. Scrivi una funzione che restituisce il valore massimo per una chiave da una lista di dizionari.

In [10]:
def max_value(lst:list,key:str) -> int:
    if len(lst) == 0:
        return None

    found = False
    max_val = None

    for dictionary in lst:
        if key in dictionary:
            if not found:
                max_val = dictionary[key]
                found = True
            elif dictionary[key] > max_val:
                max_val = dictionary[key]

    return max_val

# Test con vari casi
test_dict1 = [{'prezzo': 10, 'quantità': 5},
              {'prezzo': 20, 'quantità': 3},
              {'prezzo': 15, 'quantità': 4}]

test_dict2 = [{'voto': -2, 'peso': 1},
              {'voto': -5, 'peso': 2},
              {'voto': -1, 'peso': 3}]

test_dict3 = []  # lista vuota

test_dict4 = [{'nome': 'Mario', 'età': 30},
              {'nome': 'Luigi', 'età': 25},
              {'nome': 'Peach', 'età': 28}]

# Test dei casi
print(max_value(test_dict1, 'prezzo'))    # Dovrebbe restituire 20
print(max_value(test_dict2, 'voto'))      # Dovrebbe restituire -1 (massimo tra negativi)
print(max_value(test_dict3, 'chiave'))    # Dovrebbe gestire la lista vuota
print(max_value(test_dict4, 'età'))       # Dovrebbe restituire 30
print(max_value(test_dict1, 'inesistente'))  # Dovrebbe gestire chiave non presente


20
-1
None
30
None


### 10. Scrivi una funzione che prende una lista di tuple e restituisce la somma dei secondi elementi.

In [11]:
def sumtuples (lst:list) -> int:
    if len(lst) == 0:
        return None
    somma = 0
    for tupla in lst:
        somma += tupla[1]

    return somma

# Test con vari casi
test1 = [(1, 2), (3, 4), (5, 6)]           # Dovrebbe restituire 12 (2 + 4 + 6)
test2 = [('a', 1), ('b', 2), ('c', 3)]     # Dovrebbe restituire 6 (1 + 2 + 3)
test3 = [(0, -1), (0, -2), (0, -3)]        # Dovrebbe restituire -6 (-1 + -2 + -3)
test4 = []                                  # Dovrebbe restituire None (lista vuota)
test5 = [(1, 0)]                           # Dovrebbe restituire 0

print(sumtuples(test1))  # 12
print(sumtuples(test2))  # 6
print(sumtuples(test3))  # -6
print(sumtuples(test4))  # None
print(sumtuples(test5))  # 0


12
6
-6
None
0


### 11. Crea una classe Person con nome e eta, e un metodo che stampa un saluto.

In [12]:
class Person:
    def __init__(self,nome,eta):
        self.nome = nome
        self.eta = eta
    def __repr__(self):
        return f'Ciao! Il tuo nome è:{self.nome} e la tua età è:{self.eta}'

# Test con vari casi
persona1 = Person("Mario", 25)
persona2 = Person("Anna", 30)
persona3 = Person("", 0)       # Test con valori vuoti/zero
persona4 = Person("Luigi", 17) # Test con un minorenne

persona1.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Mario e la tua età è:25
persona2.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Anna e la tua età è:30
persona3.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è: e la tua età è:0
persona4.__repr__()  # Dovrebbe stampare: Ciao! Il tuo nome è:Luigi e la tua età è:17


'Ciao! Il tuo nome è:Luigi e la tua età è:17'

### 12. Crea una classe BankAccount con saldo, deposito e prelievo.

In [13]:
class BankAccount:
    def __init__(self,saldo):
        self.saldo = saldo

    def deposito(self,deposito):
        if deposito < 0:
            return False
        self.saldo += deposito
        return True

    def prelievo(self,prelievo):
        if prelievo > self.saldo or prelievo < 0:
            return False
        self.saldo = self.saldo - prelievo
        return True

# Test con vari casi
conto = BankAccount(1000)
print(conto.deposito(500))      # True (deposito riuscito)
print(conto.saldo)              # 1500
print(conto.deposito(-100))     # False (importo negativo)
print(conto.saldo)              # 1500 (saldo non modificato)
print(conto.prelievo(2000))     # False (saldo insufficiente)
print(conto.saldo)              # 1500 (saldo non modificato)
print(conto.prelievo(500))      # True (prelievo riuscito)
print(conto.saldo)              # 1000

True
1500
False
1500
False
1500
True
1000


### 13. Override del metodo __str__ in una classe Car.

In [14]:
class Car:
    def __init__(self,nome,marca,modello):
        self.nome = nome
        self.marca = marca
        self.modello = modello
    def __str__(self):
        return f'La macchina è:{self.nome}\n La marca è:{self.marca}\n Il modello è: {self.modello} '


# Test con vari casi
auto1 = Car("500", "Fiat", "Sport")
auto2 = Car("Model S", "Tesla", "Long Range")
auto3 = Car("Urus", "Lamborghini", "S")

# Test stampa diretta
print(auto1)  # Dovrebbe mostrare: La macchina è:500 La marca è:Fiat Il modello è: Sport
print(auto2)  # Dovrebbe mostrare: La macchina è:Model S La marca è:Tesla Il modello è: Long Range
print(auto3)  # Dovrebbe mostrare: La macchina è:Urus La marca è:Lamborghini Il modello è: S

# Test conversione esplicita a stringa
stringa_auto = str(auto1)
print(stringa_auto)  # Dovrebbe mostrare lo stesso output di print(auto1)


La macchina è:500
 La marca è:Fiat
 Il modello è: Sport 
La macchina è:Model S
 La marca è:Tesla
 Il modello è: Long Range 
La macchina è:Urus
 La marca è:Lamborghini
 Il modello è: S 
La macchina è:500
 La marca è:Fiat
 Il modello è: Sport 


### 14. Crea una classe Rectangle con metodi per area e perimetro.

In [15]:
class Rectangle:
    def __init__(self,base,altezza):
        self.base = base
        self.altezza = altezza
    def area(self):
        return self.base * self.altezza
    def perimetro(self):
        return (self.base*2)+(self.altezza*2)

# Test con vari casi
rettangolo1 = Rectangle(5, 3)      # rettangolo 5x3
rettangolo2 = Rectangle(10, 10)    # quadrato 10x10
rettangolo3 = Rectangle(2.5, 4)    # rettangolo con decimali
rettangolo4 = Rectangle(0, 5)      # rettangolo con base zero

# Test calcolo area
print(rettangolo1.area())      # Dovrebbe stampare 15 (5 * 3)
print(rettangolo2.area())      # Dovrebbe stampare 100 (10 * 10)
print(rettangolo3.area())      # Dovrebbe stampare 10.0 (2.5 * 4)
print(rettangolo4.area())      # Dovrebbe stampare 0 (0 * 5)

# Test calcolo perimetro
print(rettangolo1.perimetro())  # Dovrebbe stampare 16 ((5 * 2) + (3 * 2))
print(rettangolo2.perimetro())  # Dovrebbe stampare 40 ((10 * 2) + (10 * 2))
print(rettangolo3.perimetro())  # Dovrebbe stampare 13.0 ((2.5 * 2) + (4 * 2))
print(rettangolo4.perimetro())  # Dovrebbe stampare 10 ((0 * 2) + (5 * 2))


15
100
10.0
0
16
40
13.0
10


### 15. Crea una classe Student con lista voti e media.

In [16]:
class Student:
    def __init__(self, nome, voti):
        self.nome = nome
        self.voti = voti

    def media(self):
        if len(self.voti) == 0:
            return 0
        return sum(self.voti) / len(self.voti)  # Usa la funzione built-in sum

# Test con vari casi
studente1 = Student("Mario", [18, 25, 30, 28])
studente2 = Student("Luigi", [30, 30, 30])
studente3 = Student("Anna", [])
studente4 = Student("Luca", [18, 18, 18, 18])
studente5 = Student("Elena", [25, 28, 27, 26])

# Test stampa voti
print(f"{studente1.nome}: voti = {studente1.voti}")
print(f"{studente2.nome}: voti = {studente2.voti}")
print(f"{studente3.nome}: voti = {studente3.voti}")

# Test calcolo media
print(f"La media di {studente1.nome} è: {studente1.media()}")  # Dovrebbe essere circa 25.25
print(f"La media di {studente2.nome} è: {studente2.media()}")  # Dovrebbe essere 30.0
print(f"La media di {studente3.nome} è: {studente3.media()}")  # Dovrebbe essere 0
print(f"La media di {studente4.nome} è: {studente4.media()}")  # Dovrebbe essere 18.0
print(f"La media di {studente5.nome} è: {studente5.media()}")  # Dovrebbe essere 26.5

Mario: voti = [18, 25, 30, 28]
Luigi: voti = [30, 30, 30]
Anna: voti = []
La media di Mario è: 25.25
La media di Luigi è: 30.0
La media di Anna è: 0
La media di Luca è: 18.0
La media di Elena è: 26.5


### 16. Crea una classe Animal e una sottoclasse Dog che override speak().

In [17]:
class Animal:
    def __init__(self,nome):
        self.nome = nome
    def speak(self):
        return "L'animale fa un verso"
class Dog(Animal):
    def __init__(self,nome):
        super().__init__(nome)
    def speak(self):
        return 'Il cane abbaia'

# Test con vari casi
animale = Animal("generico")
cane = Dog("Fido")

# Test del metodo speak() per entrambe le classi
print(animale.speak())    # Dovrebbe stampare "L'animale fa un verso"
print(cane.speak())       # Dovrebbe stampare "Il cane abbaia"

# Test con nome
print(animale.nome)       # Dovrebbe stampare "generico"
print(cane.nome)         # Dovrebbe stampare "Fido"

# Test con diversi cani
cane2 = Dog("Rex")
print(cane2.speak())      # Dovrebbe stampare "Il cane abbaia"
print(cane2.nome)        # Dovrebbe stampare "Rex"



L'animale fa un verso
Il cane abbaia
generico
Fido
Il cane abbaia
Rex


### 17. Due oggetti Book sono uguali se titolo e autore coincidono.

In [18]:
class Book:
    def __init__(self,nome,autore):
        self.nome = nome
        self.autore = autore
    def __eq__(self, other):
        if type(self) == type(other):
            return (self.nome == other.nome) and (self.autore == other.autore)
        else:
            return False

# Test con vari casi
libro1 = Book("Il Signore degli Anelli", "Tolkien")
libro2 = Book("Il Signore degli Anelli", "Tolkien")  # Stesso libro
libro3 = Book("Il Signore degli Anelli", "Smith")    # Stesso titolo, autore diverso
libro4 = Book("Harry Potter", "Rowling")             # Libro completamente diverso
altro_oggetto = "Non un libro"                       # Test con tipo diverso

# Test di uguaglianza
print(libro1 == libro2)  # Dovrebbe stampare True
print(libro1 == libro3)  # Dovrebbe stampare False
print(libro1 == libro4)  # Dovrebbe stampare False
print(libro1 == altro_oggetto)  # Dovrebbe stampare False

# Test con attributi
print(libro1.nome)    # Dovrebbe stampare "Il Signore degli Anelli"
print(libro1.autore)  # Dovrebbe stampare "Tolkien"



True
False
False
False
Il Signore degli Anelli
Tolkien


### 18. Crea una Shape astratta con area(), da implementare in Circle e Square.

In [19]:
# 1. Importa ABC e abstractmethod dal modulo abc
from abc import ABC, abstractmethod

# 2. Crea la classe astratta ereditando da ABC
class Shape(ABC):

    def __init__(self, nome):
        self.nome = nome

    # 3. Dichiara i metodi astratti con il decoratore
    @abstractmethod
    def calcola_area(self):
        """Metodo astratto per calcolare l'area."""
        pass # Non c'è bisogno di codice qui

class Quadrato(Shape):

    def __init__(self, lato):
        super().__init__("Quadrato") # Chiama il costruttore della classe padre
        self.lato = lato

    # Implementazione OBBLIGATORIA del metodo astratto
    def calcola_area(self):
        return self.lato ** 2
class Cerchio(Shape):

    def __init__(self,raggio):
        super().__init__('Cerchio')
        self.raggio = raggio
    def calcola_area(self):
        return 2*3.14*(self.raggio**2)

# Test
quadrato = Quadrato(5)
cerchio = Cerchio(3)

print(quadrato.calcola_area())   # Dovrebbe stampare 25
print(cerchio.calcola_area())    # Dovrebbe stampare 56.52


25
56.52


### 19. Crea una classe Counter che incrementa solo se il valore e pari.

In [20]:
class Counter:
    def __init__(self,count):
        self.count = count
    def counter(self,number):
        if number % 2 == 0:
            self.count += number

# Test con vari casi
contatore = Counter(0)

# Incremento con numero pari
contatore.counter(2)  # Dovrebbe incrementare il contatore a 2
print(contatore.count)  # Dovrebbe stampare 2

# Incremento con numero dispari
contatore.counter(3)  # Non dovrebbe cambiare il contatore
print(contatore.count)  # Dovrebbe stampare 2

# Incremento con numero pari negativo
contatore.counter(-4)  # Dovrebbe decrementare il contatore a -2
print(contatore.count)  # Dovrebbe stampare -2

# Incremento con zero
contatore.counter(0)  # Non dovrebbe cambiare il contatore
print(contatore.count)  # Dovrebbe stampare -2

2
2
-2
-2


### 20. Crea una classe Timer con start, stop e elapsed.

In [21]:
class Timer:
    def __init__(self,start,stop):
        self.start = start
        self.stop = stop
        self.elapsed = stop - start
# Test con vari casi
timer1 = Timer(0, 10)  # Timer con start 0 e stop 10
print(timer1.elapsed)  # Dovrebbe stampare 10

timer2 = Timer(5, 20)  # Timer con start 5 e stop 20
print(timer2.elapsed)  # Dovrebbe stampare 15

timer3 = Timer(10, 10)  # Timer con start e stop uguali
print(timer3.elapsed)  # Dovrebbe stampare 0

timer4 = Timer(15, 5)  # Timer con start maggiore di stop
print(timer4.elapsed)  # Dovrebbe stampare -10

10
15
0
-10


### 21. Usa lambda per ordinare tuple in base al secondo elemento.

In [22]:
# Lista di tuple (es. prodotto, quantità)
lista_tuple = [('Mela', 50), ('Banana', 25), ('Arancia', 100), ('Kiwi', 10)]

lista_ordinata = sorted(lista_tuple,key= lambda x: x[1])

print(lista_ordinata)


[('Kiwi', 10), ('Banana', 25), ('Mela', 50), ('Arancia', 100)]


### 22. Usa filter per tenere solo numeri > 100.

In [23]:
numeri_da_filtrare = [25, 158, 99, 100, 101, -10, 500, 0, 100.5]

numeri_filtrati = list(filter(lambda x: x>100,numeri_da_filtrare))

print(numeri_filtrati)


[158, 101, 500, 100.5]


### 23. Usa map per convertire stringhe in uppercase.

In [24]:
parole_da_trasformare = ["ciao", "Mondo", "PYTHON", "Test con Numeri 123", "", "a"]

parole_trasformate = list(map(lambda s: s.upper(),parole_da_trasformare))
print(parole_trasformate)


['CIAO', 'MONDO', 'PYTHON', 'TEST CON NUMERI 123', '', 'A']


### 24. Usa reduce per calcolare il prodotto degli elementi.

In [25]:
from functools import reduce
numeri_da_moltiplicare = [2, 3, 5, -4, 1]

prodotto = reduce(lambda x, y: x * y, numeri_da_moltiplicare)
print(prodotto)

-120


### 25. Scrivi una lambda che restituisce il maggiore tra due numeri.

In [26]:
coppie_di_test = [
    (10, 5),
    (3, 8),
    (7, 7),
    (4, -2),
    (-5, -10),
    (0, 9)
]

trova_maggiore = lambda x, y: x if x > y else y

# 2. Itera attraverso le coppie di test.
for coppia in coppie_di_test:
    # 3. 'spacchetta' la tupla in due variabili separate per chiarezza.
    num1, num2 = coppia

    # 4. CHIAMA la funzione con i due numeri e salva il risultato.
    risultato = trova_maggiore(num1, num2)

    # 5. Stampa il RISULTATO, non la funzione.
    print(f"Tra {num1} e {num2}, il maggiore è: {risultato}")


Tra 10 e 5, il maggiore è: 10
Tra 3 e 8, il maggiore è: 8
Tra 7 e 7, il maggiore è: 7
Tra 4 e -2, il maggiore è: 4
Tra -5 e -10, il maggiore è: -5
Tra 0 e 9, il maggiore è: 9


### 26. Crea un array 3x3 di zeri.

In [27]:
array = np.zeros((3,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 27. Genera un array 4x4 con numeri casuali tra 0 e 1.

In [28]:
from numpy.random._examples.cffi.extending import rng

# Genera un singolo float
random_float = rng.random()
random_array = rng.random(16)
print(f"Array di 5 float casuali:\n{random_array}")

random_matrix = rng.random(size=(4, 4))
print(f"Matrice 2x3 di float casuali:\n{random_matrix}")

Array di 5 float casuali:
[0.67643841 0.52487759 0.39468276 0.67546223 0.05337678 0.65535222
 0.67013    0.40515072 0.76159592 0.47242005 0.80148075 0.80596615
 0.89946493 0.83964074 0.096749   0.07301098]
Matrice 2x3 di float casuali:
[[0.96994669 0.95341186 0.27283239 0.18230198]
 [0.17929432 0.83085759 0.24940513 0.07392941]
 [0.38047129 0.99546612 0.93295822 0.41212399]
 [0.8966292  0.78588609 0.91193187 0.65498314]]


### 28. Crea array da 1 a 20, sostituisci multipli di 4 con -1.

In [29]:
array = np.arange(1,21)
print(array)
mask = array %4 == 0
print(mask)
array[mask] = -1
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False False False  True False False False  True False False False  True
 False False False  True False False False  True]
[ 1  2  3 -1  5  6  7 -1  9 10 11 -1 13 14 15 -1 17 18 19 -1]


### 29. Calcola la media di ogni colonna di un array 5x5.

In [30]:
array = np.random.randint(0,100,(5,5))
print(array)
media =  np.mean(array,axis = 0) # Colonna  = 0, Riga = 1
print(media)


[[90 64 37 95 68]
 [23 15 51  0 52]
 [39 46 36 69 91]
 [26  4 96 66  6]
 [56 91 17 86  4]]
[46.8 44.  47.4 63.2 44.2]


### 30. Conta i valori > 10 in un array 10x10 casuale.

In [31]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array > 10).sum()

print(count)

[[71 28 77 43 31 67 41 20 18 37]
 [96 42 23 83 22 19  8 36 75  6]
 [59 65 17 16 21 15 13 76 37 21]
 [ 9 35 61 31 38 76 14  5 31 84]
 [77  5 67 12 17 27 42 19 12 83]
 [ 6 52 52  8 74 18 18 43 16 71]
 [93 84 28 56 63 32 74 89 75 84]
 [75 55  0 90 32 58 72 99 78 78]
 [99 56 40 11 75 48 23 79  0 57]
 [61 64 98 55 53  5 26 38 70 68]]
90


### 31. Conta valori dispari negativi in un array.

In [32]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array % 2 != 0).sum()

print(count)


[[55 60 95 23 81 56 86 50 78  2]
 [10 31 69 32 21 21 63 64 53 75]
 [59 84 21  6 71 45 54 41 56  9]
 [74 15 69 89 60 63 12 59 93  3]
 [27 98 19 89 58 50 24  6 23 10]
 [48  8 81 99 16  7 91 90 78 18]
 [89 70 27 68 85 83  7 49  8 97]
 [31  3 87 46 30 78 71 54 52 20]
 [79 11 26 61  0 33 27 73 74 70]
 [35 70  4 71 43 91  3 84 27 74]]
55


### 32. Restituisci array booleano per i multipli di 7.

In [33]:
array = np.random.randint(0,100,(10,10))
print(array)

count = (array % 7 != 0).sum()

print(count)


[[33 18 88 25 61 70 91 11 61 79]
 [79 76 89 37  9 93 94 72 97 38]
 [31 58  9 63 15 30 14 18  6 72]
 [93 12 52 27 75 32 91 39 28 65]
 [88 74 14 10 81 74 26 54 99 35]
 [89 51 26  8 13  6 12  4 60 51]
 [13 36 33 55 53 84 95 11 63 42]
 [75  7 46 38 38 92 23 53 32 30]
 [43 26 85 42 19 41 82 12 47 15]
 [55 22 65 15 56 94 12 46 32 24]]
86


### 33. Normalizza un array (media 0, std 1).

In [34]:
array = np.random.randint(0,100,(10,10))
print('Array pre Standardizzazione: \n')
print(array)
print('\n')
media = array.mean()
# Potresti anche usare np.mean(punteggi)

# 3. Calcoliamo la deviazione standard (σ)
dev_std = array.std()

array = array - media / dev_std
print('Array Post Standardizzazione: \n')
print(array)



Array pre Standardizzazione: 

[[33 99 77 25 89 37 72 28 96 68]
 [37 76 36 42 67 16 11 97 47  7]
 [16 58 16  7  9 37 25 43 92 68]
 [23 45 30 32 66 97 84 95 14 52]
 [24 43 96 43  4 32  9 47 56 43]
 [68 31 89 81  0 67 80 61  9 50]
 [24 45 86 15 95 84 29 69 77 72]
 [77  4 81 81 22 67 39 28 27 41]
 [52 48 46 28 40 85 85 28 37 12]
 [92 24 70 97 90 41 84 76 50 76]]


Array Post Standardizzazione: 

[[31.18781262 97.18781262 75.18781262 23.18781262 87.18781262 35.18781262
  70.18781262 26.18781262 94.18781262 66.18781262]
 [35.18781262 74.18781262 34.18781262 40.18781262 65.18781262 14.18781262
   9.18781262 95.18781262 45.18781262  5.18781262]
 [14.18781262 56.18781262 14.18781262  5.18781262  7.18781262 35.18781262
  23.18781262 41.18781262 90.18781262 66.18781262]
 [21.18781262 43.18781262 28.18781262 30.18781262 64.18781262 95.18781262
  82.18781262 93.18781262 12.18781262 50.18781262]
 [22.18781262 41.18781262 94.18781262 41.18781262  2.18781262 30.18781262
   7.18781262 45.18781262 54.1

### 34. Da una lista di array, restituisci quello con std maggiore.

In [53]:
def trova_array_std_max(lst:list) -> np.ndarray:
    # Gestisce il caso di una lista vuota per evitare un errore da max()
    if not lst:
        return None

    # Usa la funzione max() con una chiave per trovare l'array
    # che massimizza il valore restituito da np.std
    return max(lst, key=np.std)

# Array con bassa dispersione
array1 = np.array([10, 11, 12, 13, 14])
# print(f"Std di array1: {np.std(array1):.2f}") # ~1.41

# Array con alta dispersione
array2 = np.array([0, 10, 20, 30, 40])
# print(f"Std di array2: {np.std(array2):.2f}") # ~14.14

# Array con dispersione media
array3 = np.array([5, 10, 15])
# print(f"Std di array3: {np.std(array3):.2f}") # ~4.08

lista_test_1 = [array1, array2, array3]



# Array con dispersione
array_a = np.array([1, 5, 9])
# print(f"Std di array_a: {np.std(array_a):.2f}") # ~3.27

# Array senza dispersione (std = 0)
array_b = np.array([7, 7, 7, 7, 7])
# print(f"Std di array_b: {np.std(array_b):.2f}") # 0.00

lista_test_2 = [array_a, array_b]

# Risultato atteso: array_a
# Risultato atteso: array2, perché i suoi valori sono molto più "sparpagliati".


# Array corto ma con alta dispersione
array_x = np.array([-100, 0, 100])
# print(f"Std di array_x: {np.std(array_x):.2f}") # ~81.65

# Array più lungo ma con bassa dispersione
array_y = np.array([-1, 0, 1, 2, 3, 4, 5])
# print(f"Std di array_y: {np.std(array_y):.2f}") # ~2.0

lista_test_3 = [array_x, array_y]



# 1. Lista vuota
lista_vuota = []
# Risultato atteso: La funzione dovrebbe gestirlo senza errori,
# magari restituendo None o sollevando un'eccezione.

# 2. Lista che contiene un array vuoto
# Nota: np.std([]) produce un warning e restituisce nan (Not a Number)
array_pieno = np.array([1, 10, 100])
array_vuoto = np.array([])
lista_con_vuoto = [array_pieno, array_vuoto]
# Risultato atteso: La funzione dovrebbe ignorare l'array vuoto e restituire array_pieno.
# Risultato atteso: array_x
# --- Esegui i test ---
print("--- Test 1 ---")
risultato1 = trova_array_std_max(lista_test_1)
print(f"Array con std maggiore: \n{risultato1}")
print(f"Risultato atteso: \n{np.array([0, 10, 20, 30, 40])}")

print("\n--- Test 2 ---")
risultato2 = trova_array_std_max(lista_test_2)
print(f"Array con std maggiore: \n{risultato2}")
print(f"Risultato atteso: \n{np.array([1, 5, 9])}")

print("\n--- Test 3 ---")
risultato3 = trova_array_std_max(lista_test_3)
print(f"Array con std maggiore: \n{risultato3}")
print(f"Risultato atteso: \n{np.array([-100, 0, 100])}")

print("\n--- Test 4 (Casi Limite) ---")
risultato4_vuota = trova_array_std_max(lista_vuota)
print(f"Test con lista vuota: {risultato4_vuota}")
print("Risultato atteso: None (o un messaggio di errore gestito)")

risultato4_con_vuoto = trova_array_std_max(lista_con_vuoto)
print(f"Test con array vuoto nella lista: \n{risultato4_con_vuoto}")
print(f"Risultato atteso: \n{np.array([1, 10, 100])}")


--- Test 1 ---
Array con std maggiore: 
[ 0 10 20 30 40]
Risultato atteso: 
[ 0 10 20 30 40]

--- Test 2 ---
Array con std maggiore: 
[1 5 9]
Risultato atteso: 
[1 5 9]

--- Test 3 ---
Array con std maggiore: 
[-100    0  100]
Risultato atteso: 
[-100    0  100]

--- Test 4 (Casi Limite) ---
Test con lista vuota: None
Risultato atteso: None (o un messaggio di errore gestito)
Test con array vuoto nella lista: 
[  1  10 100]
Risultato atteso: 
[  1  10 100]


### 35. Restituisci il valore piu frequente in un array.

In [72]:
def trova_valore_piu_frequente(arr):
    if len(arr) == 0:
        return None

    array_val,array_count = np.unique(arr,return_counts=True)

    #print('DEBUG:\n ARRAY COUNT :',array_count)
    indice = np.argmax(array_count)
    #print('DEBUG: \n INDEX:',indice)
    #print('DEBUG:\n ARRAY VAL : ',array_val)

    return array_val[indice]


 # --- Set di Test ---
# 1. Vincitore chiaro
array1 = np.array([1, 2, 3, 2, 4, 2, 5, 2])
# 2. Pareggio
array2 = np.array([1, 1, 1, 2, 3, 4, 4, 4, 5])
# 3. Tutti unici
array3 = np.array([10, 20, 30, 40, 50])
# 4. Negativi e zero
array4 = np.array([-5, 0, 1, -5, 2, 0, -5])
# 5. Multi-dimensionale
array5 = np.array([[9, 1, 2], [3, 9, 9], [4, 5, 9]])
# 6. Array vuoto
array_vuoto = np.array([])

# --- Esecuzione e Verifica dei Test ---
print("--- Esercizio 35: Trova il valore più frequente ---")

print(f"\nTest 1 (Vincitore chiaro): {array1}")
print(f"Risultato: {trova_valore_piu_frequente(array1)}, Atteso: 2")

print(f"\nTest 2 (Pareggio): {array2}")
print(f"Risultato: {trova_valore_piu_frequente(array2)}, Atteso: 1")

print(f"\nTest 3 (Tutti unici): {array3}")
print(f"Risultato: {trova_valore_piu_frequente(array3)}, Atteso: 10")

print(f"\nTest 4 (Negativi e zero): {array4}")
print(f"Risultato: {trova_valore_piu_frequente(array4)}, Atteso: -5")

print(f"\nTest 5 (Multi-dimensionale): {array5.flatten()}")
print(f"Risultato: {trova_valore_piu_frequente(array5)}, Atteso: 9")

print(f"\nTest 6 (Array vuoto): {array_vuoto}")
print(f"Risultato: {trova_valore_piu_frequente(array_vuoto)},Atteso: None")

--- Esercizio 35: Trova il valore più frequente ---

Test 1 (Vincitore chiaro): [1 2 3 2 4 2 5 2]
Risultato: 2, Atteso: 2

Test 2 (Pareggio): [1 1 1 2 3 4 4 4 5]
Risultato: 1, Atteso: 1

Test 3 (Tutti unici): [10 20 30 40 50]
Risultato: 10, Atteso: 10

Test 4 (Negativi e zero): [-5  0  1 -5  2  0 -5]
Risultato: -5, Atteso: -5

Test 5 (Multi-dimensionale): [9 1 2 3 9 9 4 5 9]
Risultato: 9, Atteso: 9

Test 6 (Array vuoto): []
Risultato: None,Atteso: None


n### 36. Divisione sicura tra due numeri con gestione divisione per zero.

In [74]:
def divzero(a:int,b:int) -> int:
    try:
        return a/b
    except ZeroDivisionError:
        print("Non si può fare la divisione per zero!")
        return None

# --- Set di Test ---
# Creiamo una lista di tuple, dove ogni tupla è una coppia (numeratore, denominatore)
casi_di_test = [
    (10, 2),      # Caso standard
    (9, 3),       # Divisione intera
    (5, 2),       # Divisione con risultato float
    (-10, 2),     # Divisione con numero negativo
    (0, 5),       # Divisione di zero per un numero
    (10, 0),      # Caso critico: divisione per zero
    (-8, -4)      # Divisione tra negativi
]

# --- Esecuzione e Verifica dei Test ---
print("--- Esercizio 36: Test della divisione sicura ---")

for numeratore, denominatore in casi_di_test:
    print(f"\nTest con: {numeratore} / {denominatore}")
    risultato = divzero(numeratore, denominatore)
    print(f"Risultato: {risultato}")

--- Esercizio 36: Test della divisione sicura ---

Test con: 10 / 2
Risultato: 5.0

Test con: 9 / 3
Risultato: 3.0

Test con: 5 / 2
Risultato: 2.5

Test con: -10 / 2
Risultato: -5.0

Test con: 0 / 5
Risultato: 0.0

Test con: 10 / 0
Non si può fare la divisione per zero!
Risultato: None

Test con: -8 / -4
Risultato: 2.0


### 37. Accetta solo liste, stampa errore altrimenti.

In [78]:
def accetta_solo_liste(lst:list):
    if isinstance(lst,list):
        print('OK è una lista')
    else:
        print('ERRORE, Volevo una lista come input')

# --- Set di Test ---

# 1. Casi validi (dovrebbero stampare "OK")
casi_validi = [
    [1, 2, 3],          # Lista di interi standard
    [],                 # Caso limite: lista vuota
    ["a", "b", "c"],    # Lista di stringhe
    [1, "test", True]   # Lista con tipi di dati misti
]

# 2. Casi non validi (dovrebbero stampare "ERRORE")
casi_non_validi = [
    "questa non è una lista", # Stringa
    123,                      # Intero
    3.14,                     # Float
    (1, 2, 3),                # Tupla (molto simile a una lista, ottimo test)
    {'a': 1, 'b': 2},         # Dizionario
    {1, 2, 3},                # Set
    True,                     # Booleano
    None                      # NoneType
]

# --- Esecuzione e Verifica dei Test ---
print("--- Esercizio 37: Test di accettazione delle liste ---")

print("\n--- Test con input VALIDI ---")
for test in casi_validi:
    accetta_solo_liste(test)

print("\n--- Test con input NON VALIDI ---")
for test in casi_non_validi:
    accetta_solo_liste(test)

--- Esercizio 37: Test di accettazione delle liste ---

--- Test con input VALIDI ---
OK è una lista
OK è una lista
OK è una lista
OK è una lista

--- Test con input NON VALIDI ---
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input
ERRORE, Volevo una lista come input


### 38. Accetta solo array Numpy, restituisce massimo o errore.

In [81]:
def massimo(arr:np.ndarray) -> int:
    try:
        return np.max(arr)
    except TypeError:
        print('ERRORE: tipo di input sbagliato')
        return None
    except ValueError:
        # Aggiunta: np.max() su un array vuoto solleva ValueError.
        print("ERRORE: L'array è vuoto, non è possibile trovare un massimo.")
        return None

# --- Set di Test ---

# 1. Casi validi (dovrebbero restituire un numero)
casi_validi = [
    np.array([1, 5, 2, 8, 3]),      # Array di interi standard
    np.array([-10, -5, -1, -20]),   # Array con numeri negativi
    np.array([15.5, 15.1, 15.9]),   # Array con numeri float
    np.array([[1, 2], [9, 4]])      # Array multi-dimensionale
]

# 2. Casi non validi (dovrebbero attivare l'errore)
casi_non_validi = [
    [1, 5, 2, 8, 3],                # Lista Python (il caso più comune di errore)
    "non sono un array",            # Stringa
    123,                            # Intero
    {'a': 1, 'b': 5}                # Dizionario
]

# 3. Caso limite (gestito con l'except ValueError)
array_vuoto = np.array([])

# --- Esecuzione e Verifica dei Test ---
print("--- Esercizio 38: Test della funzione 'massimo' ---")

print("\n--- Test con input VALIDI (array NumPy) ---")
for i, test_array in enumerate(casi_validi):
    risultato = massimo(test_array)
    print(f"Test {i+1}: Il massimo di {test_array.flatten()} è: {risultato}")

print("\n--- Test con input NON VALIDI ---")
for i, test_input in enumerate(casi_non_validi):
    print(f"Test {i+1} (input di tipo {type(test_input).__name__}):")
    massimo(test_input)

print("\n--- Test con caso limite (array vuoto) ---")
print(f"Test con array vuoto:")
massimo(array_vuoto)

--- Esercizio 38: Test della funzione 'massimo' ---

--- Test con input VALIDI (array NumPy) ---
Test 1: Il massimo di [1 5 2 8 3] è: 8
Test 2: Il massimo di [-10  -5  -1 -20] è: -1
Test 3: Il massimo di [15.5 15.1 15.9] è: 15.9
Test 4: Il massimo di [1 2 9 4] è: 9

--- Test con input NON VALIDI ---
Test 1 (input di tipo list):
Test 2 (input di tipo str):
ERRORE: tipo di input sbagliato
Test 3 (input di tipo int):
Test 4 (input di tipo dict):

--- Test con caso limite (array vuoto) ---
Test con array vuoto:
ERRORE: L'array è vuoto, non è possibile trovare un massimo.


### 39. Somma due liste elemento per elemento, gestendo lunghezze diverse.

In [82]:
def somma_liste(lst1:list,lst2:list) -> list:
    if len(lst1) != len(lst2):
        print('Le due liste hanno errore diverso')
        return None

    return [e1+ e2 for e1,e2 in zip(lst1,lst2)]


### 40. Apre un file e gestisce l'errore se il file non esiste.

In [83]:
try:
    file = open('../Databases/clienti.csv')
    print('File aperto correttamente')
except FileNotFoundError:
    print('Errore nella apertuna del file')


File aperto correttamente


### 41. Verifica se una stringa e palindroma.

In [86]:
def stringa_palindroma(str1:str) -> bool:
    for i in range(0, len(str1)):
        if str1[i] != str1[-1-i]:
            return False
    return True

# --- Set di Test ---

# 1. Palindromi classici
test_palindromo_1 = "anna"
test_palindromo_2 = "radar"
test_palindromo_3 = "madam"
test_palindromo_4 = "level"

# 2. Non palindromi
test_non_palindromo_1 = "hello"
test_non_palindromo_2 = "python"
test_non_palindromo_3 = "world"

# 3. Casi limite
test_stringa_vuota = ""          # Una stringa vuota è considerata un palindromo
test_singolo_carattere = "a"     # Un singolo carattere è un palindromo

# 4. Palindromi con lunghezza dispari e pari
test_palindromo_dispari = "racecar"
test_palindromo_pari = "abba"

# 5. Stringhe con spazi (la tua funzione attuale non li ignora)
test_con_spazi_palindromo = "anna anna" # Non è un palindromo se gli spazi contano
test_con_spazi_non_palindromo = "a man a plan a canal panama" # Palindromo se si ignorano spazi/punteggiatura, non se contano

# 6. Stringhe con maiuscole/minuscole (la tua funzione attuale è case-sensitive)
test_case_sensitive_palindromo = "Racecar" # Non è un palindromo se case-sensitive
test_case_sensitive_non_palindromo = "Madam" # Non è un palindromo se case-sensitive

# --- Esecuzione e Verifica dei Test ---
print("--- Esercizio 41: Test della funzione 'stringa_palindroma' ---")

print(f"\nTest Palindromi:")
print(f"'{test_palindromo_1}' è palindroma? {stringa_palindroma(test_palindromo_1)} (Atteso: True)")
print(f"'{test_palindromo_2}' è palindroma? {stringa_palindroma(test_palindromo_2)} (Atteso: True)")
print(f"'{test_palindromo_3}' è palindroma? {stringa_palindroma(test_palindromo_3)} (Atteso: True)")
print(f"'{test_palindromo_4}' è palindroma? {stringa_palindroma(test_palindromo_4)} (Atteso: True)")

print(f"\nTest Non Palindromi:")
print(f"'{test_non_palindromo_1}' è palindroma? {stringa_palindroma(test_non_palindromo_1)} (Atteso: False)")
print(f"'{test_non_palindromo_2}' è palindroma? {stringa_palindroma(test_non_palindromo_2)} (Atteso: False)")
print(f"'{test_non_palindromo_3}' è palindroma? {stringa_palindroma(test_non_palindromo_3)} (Atteso: False)")

print(f"\nTest Casi Limite:")
print(f"'{test_stringa_vuota}' è palindroma? {stringa_palindroma(test_stringa_vuota)} (Atteso: True)")
print(f"'{test_singolo_carattere}' è palindroma? {stringa_palindroma(test_singolo_carattere)} (Atteso: True)")

print(f"\nTest Lunghezza Dispari/Pari:")
print(f"'{test_palindromo_dispari}' è palindroma? {stringa_palindroma(test_palindromo_dispari)} (Atteso: True)")
print(f"'{test_palindromo_pari}' è palindroma? {stringa_palindroma(test_palindromo_pari)} (Atteso: True)")

print(f"\nTest con Spazi (case-sensitive):")
print(f"'{test_con_spazi_palindromo}' è palindroma? {stringa_palindroma(test_con_spazi_palindromo)} (Atteso: False)")
print(f"'{test_con_spazi_non_palindromo}' è palindroma? {stringa_palindroma(test_con_spazi_non_palindromo)} (Atteso: False)")

print(f"\nTest con Maiuscole/Minuscole (case-sensitive):")
print(f"'{test_case_sensitive_palindromo}' è palindroma? {stringa_palindroma(test_case_sensitive_palindromo)} (Atteso: False)")
print(f"'{test_case_sensitive_non_palindromo}' è palindroma? {stringa_palindroma(test_case_sensitive_non_palindromo)} (Atteso: False)")

--- Esercizio 41: Test della funzione 'stringa_palindroma' ---

Test Palindromi:
'anna' è palindroma? True (Atteso: True)
'radar' è palindroma? True (Atteso: True)
'madam' è palindroma? True (Atteso: True)
'level' è palindroma? True (Atteso: True)

Test Non Palindromi:
'hello' è palindroma? False (Atteso: False)
'python' è palindroma? False (Atteso: False)
'world' è palindroma? False (Atteso: False)

Test Casi Limite:
'' è palindroma? True (Atteso: True)
'a' è palindroma? True (Atteso: True)

Test Lunghezza Dispari/Pari:
'racecar' è palindroma? True (Atteso: True)
'abba' è palindroma? True (Atteso: True)

Test con Spazi (case-sensitive):
'anna anna' è palindroma? True (Atteso: False)
'a man a plan a canal panama' è palindroma? False (Atteso: False)

Test con Maiuscole/Minuscole (case-sensitive):
'Racecar' è palindroma? False (Atteso: False)
'Madam' è palindroma? False (Atteso: False)


### 42. Simula due dadi e ritorna la somma.

In [3]:
import random

def lancia_e_somma_dadi():
    """
    Simula il lancio di due dadi a 6 facce, stampa i risultati
    e restituisce la loro somma.
    """
    dado1 = random.randint(1, 6)
    dado2 = random.randint(1, 6)

    somma_risultato = dado1 + dado2  # Calcolo diretto, nome di variabile sicuro

    print(f"Lancio: Dado 1 = {dado1}, Dado 2 = {dado2}")

    return somma_risultato

# --- Esempio di utilizzo ---
print("--- Primo lancio ---")
risultato1 = lancia_e_somma_dadi()
print(f"La somma del primo lancio è: {risultato1}")

print("\n--- Secondo lancio ---")
risultato2 = lancia_e_somma_dadi()
print(f"La somma del secondo lancio è: {risultato2}")

--- Primo lancio ---
Lancio: Dado 1 = 2, Dado 2 = 3
La somma del primo lancio è: 5

--- Secondo lancio ---
Lancio: Dado 1 = 1, Dado 2 = 3
La somma del secondo lancio è: 4


### 43. Inverti chiavi e valori di un dizionario.

In [5]:
def invert(dct:dict) -> dict:
    inverted_dict ={}
    for key,value in dct.items():
        inverted_dict[value] = key
    return inverted_dict

# --- Test con vari casi ---

# Caso 1: Dizionario standard con valori unici
test_dict1 = {'a': 1, 'b': 2, 'c': 3}
print(f"Originale: {test_dict1}")
print(f"Invertito: {invert(test_dict1)}")
# Atteso: {1: 'a', 2: 'b', 3: 'c'}

# Caso 2: Dizionario con valori duplicati
# 'd' e 'e' hanno entrambi il valore 4. Solo l'ultima associazione ('e': 4)
# verrà mantenuta per la chiave 4 nel dizionario invertito.
test_dict2 = {'x': 10, 'y': 20, 'z': 10, 'w': 30}
print(f"\nOriginale: {test_dict2}")
print(f"Invertito: {invert(test_dict2)}")
# Atteso: {10: 'z', 20: 'y', 30: 'w'} (o {10: 'x', 20: 'y', 30: 'w'} a seconda dell'ordine di iterazione, ma 'z' è l'ultima)

# Caso 3: Dizionario vuoto
test_dict3 = {}
print(f"\nOriginale: {test_dict3}")
print(f"Invertito: {invert(test_dict3)}")
# Atteso: {}

# Caso 4: Dizionario con valori non hashable (es. liste)
# Questo test causerà un TypeError se non gestito.
test_dict4 = {'item1': [1, 2], 'item2': [3, 4]}
print(f"\nOriginale: {test_dict4}")
try:
    print(f"Invertito: {invert(test_dict4)}")
except TypeError as e:
    print(f"Errore: {e} - Impossibile invertire un dizionario con valori non hashable (come le liste).")
# Atteso: Errore TypeError

# Caso 5: Dizionario con tipi di dati misti
test_dict5 = {1: 'uno', 'due': 2, (3,): 'tre'}
print(f"\nOriginale: {test_dict5}")
print(f"Invertito: {invert(test_dict5)}")
# Atteso: {'uno': 1, 2: 'due', 'tre': (3,)}

Originale: {'a': 1, 'b': 2, 'c': 3}
Invertito: {1: 'a', 2: 'b', 3: 'c'}

Originale: {'x': 10, 'y': 20, 'z': 10, 'w': 30}
Invertito: {10: 'z', 20: 'y', 30: 'w'}

Originale: {}
Invertito: {}

Originale: {'item1': [1, 2], 'item2': [3, 4]}
Errore: unhashable type: 'list' - Impossibile invertire un dizionario con valori non hashable (come le liste).

Originale: {1: 'uno', 'due': 2, (3,): 'tre'}
Invertito: {'uno': 1, 2: 'due', 'tre': (3,)}


### 44. Restituisci la sottolista con somma massima.

In [44]:
# La tua soluzione qui...


### 45. Controlla se due stringhe sono anagrammi.

In [45]:
# La tua soluzione qui...


### 46. Ordina i valori unici di un array 1D.

In [46]:
# La tua soluzione qui...


### 47. Restituisci la diagonale principale di una matrice NxN.

In [47]:
# La tua soluzione qui...


### 48. Restituisci il secondo valore massimo in un array.

In [48]:
# La tua soluzione qui...


### 49. Differenze tra elementi consecutivi in un array.

In [49]:
# La tua soluzione qui...


### 50. Costruisci un array NxN con 1 sulla diagonale e 0 altrove.

In [50]:
# La tua soluzione qui...
