# 📘 Esercitazione II
---

## 🧮 Fondamenti

In [7]:
from random import random

import numpy as np
from pandas.conftest import ordered
from scipy.cluster.hierarchy import average


# Esercizio 1
# Scrivi una funzione che, data una lista di stringhe, restituisce un dizionario in cui le chiavi sono le lunghezze delle stringhe e i valori sono il numero di volte in cui quella lunghezza compare nella lista.

def fun(lst:list) -> dict:
    dictionary = {}

    for word in lst:
        key = len(word)
        dictionary[key] = dictionary.get(key, 0) + 1

    return dictionary
l1 = ['ciao','ciao','come','va']
fun(l1)

{4: 3, 2: 1}

In [9]:
# Esercizio 2
# Scrivi una funzione che prende in input una lista di numeri interi e restituisce una nuova lista contenente solo i numeri che iniziano e finiscono con la stessa cifra (es. 121, 33).
def fun(lst:list[int]) -> list:
    l = []
    for num in lst:
        n = str(num)
        if n[0] == n[-1]:
           l.append(num)
    return l

In [10]:
# Esercizio 3
# Scrivi una funzione che prende una lista di stringhe e restituisce una nuova lista ordinata alfabeticamente senza duplicati. Assumi input corretto.
def ordinata(lst:list[str]) -> list[str]:
    lst = set(lst)
    lst = sorted(lst,reverse= False)
    return lst


In [13]:
# Esercizio 4
# Scrivi una funzione che riceve una stringa e restituisce un dizionario con il numero di vocali e consonanti presenti.

def fun(word:str) -> dict:
    dictionary = {
        'vocali':0,
        'consonanti':0
    }
    for c in word:
        c = c.upper()
        if c.isalpha():
            if c in 'AEIOU':
                dictionary['vocali'] += 1
            else:
                dictionary['consonanti'] += 1
    return dictionary

In [14]:
# Esercizio 5
# Scrivi una funzione che prende in input una lista e restituisce `True` se l’elemento centrale è maggiore di entrambi i suoi vicini, altrimenti `False`. Assumi che la lista abbia almeno 3 elementi.

def fun(lst:list) -> bool:
    if len(lst) < 3:
        print('ERRORE \n Lista minore di 3')
        return False
    elif len(lst) %2 == 0:
        print('Non esiste un elemento centrale -> lista di lunghezza pari')
        return False
    else:
        if lst[len(lst)//2-1]<lst[len(lst)//2] and lst[len(lst)//2] > lst[len(lst)//2+1]:
            return True
        else:
            return False


In [18]:
# Esercizio 6
# Scrivi una funzione che prende una stringa e restituisce il numero di parole palindrome contenute al suo interno. Le parole sono separate da spazio.
def conta_palindrome(s:str) -> int:
    if not s:
        return 0
    parole = s.split()
    conteggio = 0
    for parola in parole:
        parola_pulita = ''.join(c for c in parola if c.isalnum()).lower()

        if len(parola_pulita) > 0 and parola_pulita == parola_pulita[::-1]:
            conteggio += 1

    return conteggio

# --- Set di Test Case ---
test_cases = [
    # 1. Caso base con più palindrome
    ("i topi non avevano nipoti", 2),

    # 2. Gestione delle maiuscole
    ("Anna e Otto sono andati al lago", 2),

    # 3. Gestione della punteggiatura
    ("Wow, che bel kayak!", 2),

    # 4. Nessuna palindroma
    ("questa frase è normale", 0),

    # 5. Stringa vuota
    ("", 0),

    # 6. Stringa con solo spazi
    ("   ", 0),

    # 7. Palindrome singola
    ("radar", 1),

    # 8. Parole di una sola lettera (tecnicamente palindrome)
    ("a i o u", 4),

    # 9. Misto complesso
    ("Ehi, Anna! Ingegni, imi, ima, imi, ingegni? Mai, madam, mai!", 7)
]

# --- Esecuzione dei Test ---
for i, (test_input, expected_output) in enumerate(test_cases):
    result = conta_palindrome(test_input)
    if result == expected_output:
        print(f"✅ Test {i+1} PASSATO: Input='{test_input}', Output={result}")
    else:
        print(f"❌ Test {i+1} FALLITO: Input='{test_input}', Output={result}, Atteso={expected_output}")

✅ Test 1 PASSATO: Input='i topi non avevano nipoti', Output=2
❌ Test 2 FALLITO: Input='Anna e Otto sono andati al lago', Output=3, Atteso=2
✅ Test 3 PASSATO: Input='Wow, che bel kayak!', Output=2
❌ Test 4 FALLITO: Input='questa frase è normale', Output=1, Atteso=0
✅ Test 5 PASSATO: Input='', Output=0
✅ Test 6 PASSATO: Input='   ', Output=0
✅ Test 7 PASSATO: Input='radar', Output=1
✅ Test 8 PASSATO: Input='a i o u', Output=4
❌ Test 9 FALLITO: Input='Ehi, Anna! Ingegni, imi, ima, imi, ingegni? Mai, madam, mai!', Output=6, Atteso=7


In [24]:
# Esercizio 7
# Scrivi una funzione che prende due interi a e b, e restituisce una lista con tutti i numeri primi compresi tra a e b (inclusi).

def creazione_lista(a:int,b:int) -> list[int]:
    flag = True
    lst =[]
    massimo = max(2,a)
    for i in range(massimo,b+1):
        for j in range(2,i):
            if i % j == 0:
                flag = False
                break
        if flag:
          lst.append(i)
        flag = True
    return lst
#Esempio di utilizzo
print(f"Numeri primi tra 2 e 10: {creazione_lista(2, 10)}")   # Output: [2, 3, 5, 7]
print(f"Numeri primi tra 10 e 30: {creazione_lista(10, 30)}") # Output: [11, 13, 17, 19, 23, 29]

Numeri primi tra 2 e 10: [2, 3, 5, 7]
Numeri primi tra 10 e 30: [11, 13, 17, 19, 23, 29]


In [27]:
# Esercizio 8
# Scrivi una funzione che simula il lancio di un dado a n facce per m volte, e restituisce un dizionario con le frequenze di ogni faccia. Usa `random.randint`.
def count_lanciDadi(m:int, n:int) -> dict:
    dictionary ={}
    for i in range(1,m+1):
        numero_uscito = random.randint(1,n)
        dictionary[numero_uscito] = dictionary.get(numero_uscito, 0) + 1
    return dictionary


In [30]:
# Esercizio 9
# Scrivi una funzione che, data una lista di tuple (nome, voto), restituisce una lista con i nomi degli studenti che hanno preso un voto maggiore della media.
def well_done(grades:tuple) -> list[str]:
    total = 0
    good =[]

    for grade in grades:
        total += grade[1]
    try:
        avg = total/len(grades)
    except ZeroDivisionError:
        print('TUPlA VUOTA')
        return []
    for person in grades:
        if person[1] > avg:
            good.append(person[0])

    return good
# Esempio di utilizzo:
lista_studenti = [("Alice", 85), ("Bob", 70), ("Charlie", 90), ("David", 60)]
# Media: (85 + 70 + 90 + 60) / 4 = 305 / 4 = 76.25
# Studenti con voto > 76.25: Alice (85), Charlie (90)
print(well_done(lista_studenti)) # Output atteso: ['Alice', 'Charlie']

lista_vuota = []
print(well_done(lista_vuota)) # Output atteso: []

['Alice', 'Charlie']
TUPlA VUOTA!!!
[]


In [31]:
# Esercizio 10
# Scrivi una funzione che implementa una versione semplificata del gioco 'Pari o Dispari' tra utente e computer. Il computer sceglie un numero random da 1 a 10.

def numero() -> int:
    return random.randint(1,10)

## 🧠 Lambda & List Comprehension

In [33]:
# Esercizio 1
# Scrivi una lambda che restituisce il quadrato di un numero solo se è pari, altrimenti il numero stesso. Mostra un esempio di utilizzo.

number = lambda x: x**2 if x%2 == 0 else x

print("Value 2: ", number(2))
print('Value 3: ', number(3))

Value 2:  4
Value 3:  3


In [35]:
# Esercizio 2
# Scrivi una one-liner (usando list comprehension) che restituisce tutti i numeri da 0 a 100 divisibili per 5 e 3.
result = [i for i in range(0,100) if i % 5 == 0 and i % 3 == 0 ]
print('RESULT: ',result)

RESULT:  [0, 15, 30, 45, 60, 75, 90]


In [39]:
# Esercizio 3
# Usa una list comprehension per creare una lista di dizionari con chiave “n” e valore “n^2” per ogni n da 1 a 10.
result = [{n: n**2} for n in range(1,11)]

print('RESULT: ', result)

RESULT:  [{1: 1}, {2: 4}, {3: 9}, {4: 16}, {5: 25}, {6: 36}, {7: 49}, {8: 64}, {9: 81}, {10: 100}]


In [47]:
# Esercizio 4
# Usa `map` e `lambda` per calcolare la lunghezza di ogni parola in una lista di stringhe.
# Input di esempio
parole = ["ciao", "mondo", "Python", "è", "fantastico"]

lun = list(map(lambda parola: len(parola),parole))

print('RESULT:',lun)

RESULT: [4, 5, 6, 1, 10]


In [51]:
# Esercizio 5
# Scrivi una lambda che prende un numero `n` e restituisce una matrice identità NxN usando NumPy.

import numpy as np


matrice = lambda n: np.eye((n))
print(matrice(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 🧱 OOP

In [ ]:
# Esercizio 1
# Crea una classe `Person` con attributi nome e età. Aggiungi un metodo `is_adult()` che ritorna `True` se età ≥ 18.



In [ ]:
# Esercizio 2
# Crea una classe `BankAccount` con attributi saldo e nome_titolare. Aggiungi metodi `deposit()` e `withdraw()`.



In [ ]:
# Esercizio 3
# Crea una classe `Student` che eredita da `Person` e aggiunge l’attributo `grades` (lista). Aggiungi un metodo per calcolare la media.



In [ ]:
# Esercizio 4
# Crea due classi `Rectangle` e `Square`. Square deve ereditare da Rectangle. Implementa l’uguaglianza basata sull’area.



In [ ]:
# Esercizio 5
# Crea una classe `Timer` che memorizza un timestamp iniziale e ha un metodo `.elapsed()` che ritorna il tempo trascorso.



## 📊 NumPy

In [ ]:
# Esercizio 1
# Scrivi una funzione che crea un array 5x5 riempito con valori casuali tra -100 e 100. Restituisci solo i valori positivi pari.



In [ ]:
# Esercizio 2
# Crea una funzione che prende due array NumPy e restituisce un array contenente gli elementi comuni.



In [ ]:
# Esercizio 3
# Scrivi una funzione che crea una matrice diagonale NxN con valori crescenti sulla diagonale.



In [ ]:
# Esercizio 4
# Scrivi una funzione che crea un array 1D con 20 elementi random, poi restituisce la media degli elementi negativi.



In [ ]:
# Esercizio 5
# Scrivi una funzione che, dato un array 2D, restituisce un array con la somma di ogni colonna.



In [ ]:
# Esercizio 6
# Scrivi una funzione che prende due array 1D e restituisce il loro prodotto scalare.



In [ ]:
# Esercizio 7
# Scrivi una funzione che normalizza (z-score) un array NumPy di numeri reali.



In [ ]:
# Esercizio 8
# Scrivi una funzione che prende una matrice 3x3 e restituisce il determinante.



In [ ]:
# Esercizio 9
# Crea una funzione che prende una matrice 4x4 e restituisce la somma degli elementi sopra la diagonale.



In [ ]:
# Esercizio 10
# Scrivi una funzione che simula 1000 lanci di moneta (0 o 1) e ritorna la probabilità empirica di ottenere testa.



## 🐼 Pandas & Analisi Dati

In [ ]:
# Esercizio 1
# Scrivi una funzione che carica un file CSV e restituisce il numero di righe e colonne.



In [ ]:
# Esercizio 2
# Scrivi una funzione che riceve un DataFrame Pandas e restituisce le colonne con valori mancanti.



In [ ]:
# Esercizio 3
# Scrivi una funzione che riceve un DataFrame e restituisce il valore massimo di una colonna specificata.



In [ ]:
# Esercizio 4
# Scrivi una funzione che filtra le righe di un DataFrame dove la colonna “età” è ≥ 30.



In [ ]:
# Esercizio 5
# Crea un DataFrame fittizio con le colonne `nome`, `sesso`, `stipendio`. Calcola la media stipendi per sesso.



In [ ]:
# Esercizio 6
# Scrivi una funzione che raggruppa per colonna `categoria` e restituisce la somma di `vendite`.



In [ ]:
# Esercizio 7
# Scrivi una funzione che crea un grafico a torta con la distribuzione dei generi di un dataset di film.



In [ ]:
# Esercizio 8
# Scrivi una funzione che confronta due colonne di un DataFrame e restituisce le righe dove i valori sono uguali.



In [ ]:
# Esercizio 9
# Scrivi una funzione che salva un DataFrame in formato `.csv` e `.json`.



In [ ]:
# Esercizio 10
# Scrivi una funzione che restituisce i primi 10 record con `sort_values` su una colonna a scelta.



## 🧪 Varie

In [ ]:
# Esercizio 1
# Scrivi una funzione che legge un file di testo e restituisce il numero di parole contenute.



In [ ]:
# Esercizio 2
# Scrivi una funzione che apre un file `.json`, legge il contenuto e ritorna il valore associato a una chiave specifica.



In [ ]:
# Esercizio 3
# Scrivi una funzione che implementa una semplice calcolatrice con gestione delle eccezioni (somma, div, moltiplica).



In [ ]:
# Esercizio 4
# Scrivi una funzione che simula una coda FIFO usando una lista Python.



In [ ]:
# Esercizio 5
# Scrivi una funzione che verifica se un numero è perfetto (la somma dei suoi divisori è uguale al numero stesso).



In [ ]:
# Esercizio 6
# Scrivi una funzione che genera una password casuale lunga `n` caratteri. Usa lettere, numeri e simboli.



In [ ]:
# Esercizio 7
# Scrivi una funzione che cripta un testo usando il cifrario di Cesare con shift `k`.



In [ ]:
# Esercizio 8
# Scrivi una funzione che esegue il merge di due file `.txt`, uno riga per riga.



In [ ]:
# Esercizio 9
# Scrivi una funzione che ritorna `True` se una parola è anagramma di un’altra.



In [ ]:
# Esercizio 10
# Scrivi una funzione che prende in input una stringa e ritorna il carattere più frequente.

