# Exercises about Numpy: Creation, Attributes and Indexing

In [2]:
import numpy as np

from numpy.ma.core import argmax

## Sezione 1: Creation of Array

**1. Da Lista a Array**

Crea un array NumPy partendo dalla seguente lista Python: `[10, 20, 30, 40, 50]` e salvalo in una variabile chiamata `array_da_lista`.

In [3]:
# Il tuo codice qui
lista_python = [10, 20, 30, 40, 50]
array_da_lista = np.array(lista_python)

# Stampa l'array per verificare
print(array_da_lista)

[10 20 30 40 50]


**2. Array di Zeri**

Crea un array unidimensionale (un vettore) contenente 8 zeri e salvalo nella variabile `array_zeri`.

In [4]:
# Il tuo codice qui
array_zeri = np.zeros(8)

print(array_zeri)

[0. 0. 0. 0. 0. 0. 0. 0.]


**3. Matrice di Uni**

Crea una matrice 4x4 (4 righe, 4 colonne) contenente solo uni di tipo `float32` e salvala nella variabile `matrice_uni`.

In [5]:
# Il tuo codice qui
matrice_uni = np.full((4,4),1, dtype = float)

print(matrice_uni)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**4. Sequenza con `arange`**

Crea un array che contenga tutti i numeri interi da 20 a 60 (incluso) e salvalo in `array_seq`.

In [6]:
# Il tuo codice qui
array_seq = np.arange(20,61)

print(array_seq)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


**5. Sequenza con `linspace`**

Crea un array di 9 numeri equidistanti tra 0 e 10 (inclusi entrambi gli estremi) e salvalo in `array_space`.

In [7]:
# Il tuo codice qui
array_space = np.linspace(0,10,9)

print(array_space)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


**6. Matrice Piena**

Crea una matrice 2x6 riempita interamente con il valore `12.5` usando la funzione `np.full()` e salvala in `matrice_piena`.

In [8]:
# Il tuo codice qui
matrice_piena = np.full((2,6),12.5)

print(matrice_piena)

[[12.5 12.5 12.5 12.5 12.5 12.5]
 [12.5 12.5 12.5 12.5 12.5 12.5]]


**7. Matrice Identità**

Crea una matrice identità 6x6 e salvala in `matrice_identita`.

In [9]:
# Il tuo codice qui
matrice_identita = np.identity(6)

print(matrice_identita)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


**8. Matrice Casuale**

Crea una matrice 3x3 con numeri interi casuali compresi tra 1 e 50 e salvala in `matrice_casuale`.

In [10]:
# Il tuo codice qui
matrice_casuale = np.random.randint(50,size = (3,3))

print(matrice_casuale)

[[27 46 27]
 [38 49 42]
 [30 39 28]]


---
### Sezione 2: Attributi degli Array

Ora ispezioniamo la `matrice_casuale` creata nell'esercizio 8. Assicurati di aver eseguito la cella precedente prima di continuare.

**9. Trova la Forma**

Stampa l'attributo `shape` della `matrice_casuale`.

In [11]:
print(matrice_casuale.shape)
print(matrice_casuale.ndim)

(3, 3)
2


**10. Numero di Dimensioni**

Stampa l'attributo `ndim` della `matrice_casuale`.

In [12]:
print(matrice_casuale.ndim)

2


**11. Numero di Elementi**

Stampa l'attributo `size` della `matrice_casuale`.

In [13]:
print(matrice_casuale.size)

9


**12. Tipo di Dato**

Stampa l'attributo `dtype` della `matrice_casuale`.

In [14]:
print(matrice_casuale.dtype)

int64


---
### Sezione 3: Indicizzazione e Modifica

Per questi esercizi, lavoreremo con la seguente matrice. Esegui la cella qui sotto per crearla.

In [15]:
matrice_test = np.arange(25).reshape(5, 5)

print("Matrice di test:\n", matrice_test)

Matrice di test:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**13. Accesso Semplice**

Dalla `matrice_test`, accedi e stampa il valore `17`.

In [16]:
# Il tuo codice qui
valore_17 = matrice_test[3,2]

print(valore_17)

17


**14. Angolo in Alto a Destra**

Accedi e stampa l'elemento nell'angolo in alto a destra della `matrice_test`.

In [17]:
# Il tuo codice qui
valore_angolo_ad = matrice_test[0,4]

print(valore_angolo_ad)

4


**15. Ultimo Elemento**

Accedi e stampa l'ultimo elemento della `matrice_test` (quello nell'angolo in basso a destra) usando indici negativi.

In [18]:
# Il tuo codice qui
ultimo_valore = matrice_test[-1,-1]

print(ultimo_valore)

24


**16. Elemento Centrale**

Accedi e stampa l'elemento esatto al centro della `matrice_test`.

In [19]:
# Il tuo codice qui
elemento_centrale = matrice_test[2,2]

print(elemento_centrale)

12


**17. Modifica un Valore**

Modifica il valore `0` (in alto a sinistra) della `matrice_test` e trasformalo in `99`. Stampa la matrice per verificare la modifica.

In [20]:
# Il tuo codice qui
matrice_test[0,0] = 99

print("Matrice modificata:\n", matrice_test)

Matrice modificata:
 [[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**18. Modifica con Indici Negativi**

Modifica l'elemento nella penultima riga e ultima colonna (`19`) della `matrice_test` per farlo diventare `0`.

In [21]:
# Il tuo codice qui

matrice_test[-2,-1] = 0

print("Matrice modificata:\n", matrice_test)

Matrice modificata:
 [[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18  0]
 [20 21 22 23 24]]


**19. Il "tranello" del `dtype`**

Crea un nuovo array di interi: `array_int = np.array([10, 20, 30])`.
Poi, prova ad assegnare il valore `15.7` al suo primo elemento. Stampa l'array e osserva cosa succede al valore che hai inserito.

In [22]:
# Il tuo codice qui
array_int = np.array([10, 20, 30])
array_int[0] = 15.17

print(array_int)

[15 20 30]


**20. Lavorare sugli Zeri**

Crea una matrice 4x4 di zeri e poi modifica solo l'elemento sulla diagonale principale alla terza riga, terza colonna (indice `[2, 2]`), impostandolo a `1`.

In [23]:
# Il tuo codice qui
matrice_di_zeri = np.full((4,4),0)
matrice_di_zeri[2,2] = 1

print(matrice_di_zeri)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]


# Exercises about Numpy: Slicing, View and Modify


In [24]:
# Matrice per gli esercizi
np.random.seed(10)
matrice_esercizi = np.random.randint(0, 100, (6, 6))

print("Matrice di partenza:\n", matrice_esercizi)

Matrice di partenza:
 [[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]
 [30 30 89 12 65 31]]


**1. Estrazione del Quadrante**

Estrai la sotto-matrice 3x3 che si trova in basso a destra della `matrice_esercizi`.

In [25]:
# Il tuo codice qui
quadrante_basso_dx = matrice_esercizi[3:,3:]

print("Quadrante in basso a destra:\n", quadrante_basso_dx)

Quadrante in basso a destra:
 [[51 54 77]
 [13 92 86]
 [12 65 31]]


**2. Slicing a Scacchiera**

Estrai tutti gli elementi che si trovano su **righe con indice dispari** e **colonne con indice pari**.

In [26]:
# Il tuo codice qui
scacchiera = matrice_esercizi[::2,1::2]

print("Elementi a scacchiera:\n", scacchiera)

Elementi a scacchiera:
 [[15 28 93]
 [11 88 33]
 [13 13 86]]


**3. Inversione Parziale**

Crea una nuova matrice invertendo l'ordine delle sole righe centrali (quelle con indice 2 e 3) della `matrice_esercizi`. Le altre righe devono rimanere al loro posto.

In [27]:
# Il tuo codice qui
# Suggerimento: puoi assegnare una slice invertita a una slice normale della stessa forma.
matrice_invertita = matrice_esercizi.copy() # Lavoriamo su una copia per non modificare l'originale
matrice_invertita= matrice_invertita[::-1,::-1] # Una per riga e una per colonna

print("Matrice con righe centrali invertite:\n", matrice_invertita)

Matrice con righe centrali invertite:
 [[31 65 12 89 30 30]
 [86 92 13 25 13 69]
 [77 54 51 49 78 72]
 [33 62 88 54 11 16]
 [36 40  0 73  8 29]
 [93 89 28 64 15  9]]


**4. Bordo Esterno**

Estrai la prima e l'ultima riga della `matrice_esercizi` e salvale in una nuova variabile chiamata `bordi_orizzontali`.

*Sfida aggiuntiva (opzionale): prova a estrarre anche la prima e l'ultima colonna e a ricombinare tutto per ottenere solo il perimetro della matrice.*

In [28]:
# Il tuo codice qui

"""
Matrice di partenza:
 [[ 9 15 64 28 89 93]
 [29  8 73  0 40 36]
 [16 11 54 88 62 33]
 [72 78 49 51 54 77]
 [69 13 25 13 92 86]
 [30 30 89 12 65 31]]
"""
bordi_orizzontali = matrice_esercizi[::5,::1]
print("Prima e ultima riga:\n", bordi_orizzontali)

Prima e ultima riga:
 [[ 9 15 64 28 89 93]
 [30 30 89 12 65 31]]


**5. Modifica Tramite Vista (View)**

1.  Crea una **vista** della sotto-matrice centrale 2x2 della `matrice_esercizi`.
2.  Assegna il valore `999` a tutti gli elementi di questa vista.
3.  Stampa la `matrice_esercizi` originale per verificare che sia stata modificata.

In [29]:
# Il tuo codice qui
# 1. Crea la vista
vista_centrale = matrice_esercizi[2:4,2:4]
print("Vista prima della modifica:\n", vista_centrale)

# 2. Modifica la vista
vista_centrale[:,:] = 999

# 3. Stampa la matrice originale per verificare
print("\nMatrice originale DOPO la modifica:\n", matrice_esercizi)

Vista prima della modifica:
 [[54 88]
 [49 51]]

Matrice originale DOPO la modifica:
 [[  9  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11 999 999  62  33]
 [ 72  78 999 999  54  77]
 [ 69  13  25  13  92  86]
 [ 30  30  89  12  65  31]]


**6. Modifica Tramite Copia (Copy)**

1.  Crea una **copia** della sotto-matrice 2x2 in alto a sinistra.
2.  Assegna il valore `111` a tutti gli elementi di questa copia.
3.  Stampa sia la copia modificata che la `matrice_esercizi` originale per verificare che quest'ultima **non** sia cambiata.

In [30]:
# Il tuo codice qui
# 1. Crea la copia
copia_alto_sx = matrice_esercizi.copy()
copia_alto_sx = copia_alto_sx[:2,:2]

# 2. Modifica la copia
copia_alto_sx[:,:] = 111

# 3. Stampa per verificare
print("Copia modificata:\n", copia_alto_sx)
print("\nMatrice originale (non deve essere cambiata):\n", matrice_esercizi)

Copia modificata:
 [[111 111]
 [111 111]]

Matrice originale (non deve essere cambiata):
 [[  9  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11 999 999  62  33]
 [ 72  78 999 999  54  77]
 [ 69  13  25  13  92  86]
 [ 30  30  89  12  65  31]]


**7. Diagonali Alternate**

Estrai gli elementi sulla diagonale principale della `matrice_esercizi`, ma solo quelli che si trovano in righe con indice pari (0, 2, 4).

In [31]:
# Il tuo codice qui
# Suggerimento: puoi estrarre prima l'intera diagonale e poi fare uno slicing su di essa.
diagonale_principale = matrice_esercizi.diagonal()
print(diagonale_principale)
diagonale_alternata =diagonale_principale[::2]

print("Elementi della diagonale alternata:", diagonale_alternata)

[  9   8 999 999  92  31]
Elementi della diagonale alternata: [  9 999  92]


**8. Sovrascrivere una Colonna**

1.  Crea un nuovo array 1D di 6 elementi a tua scelta (es. `nuova_colonna = np.array([0, 0, 0, 0, 0, 0])`).
2.  Sovrascrivi l'ultima colonna della `matrice_esercizi` con questo nuovo array.

In [32]:
nuova_colonna = np.zeros(6)
matrice_esercizi[5:,::-1] = nuova_colonna
print("Matrice con l'ultima colonna sovrascritta:\n", matrice_esercizi)

Matrice con l'ultima colonna sovrascritta:
 [[  9  15  64  28  89  93]
 [ 29   8  73   0  40  36]
 [ 16  11 999 999  62  33]
 [ 72  78 999 999  54  77]
 [ 69  13  25  13  92  86]
 [  0   0   0   0   0   0]]


---
# Esercizi Avanzati su NumPy



### Sezione 1: Creazione e Manipolazione di Matrici con Schemi Specifici

**1. Matrice con Bordo**

Crea una matrice 8x8 riempita di zeri, e successivamente modifica gli elementi del bordo esterno (la prima e l'ultima riga, la prima e l'ultima colonna) in modo che contengano il valore `1`.

*Suggerimento: Puoi farlo in 4 passaggi, modificando una riga/colonna alla volta.*

In [33]:
# Il tuo codice qui
matrice_bordo = np.zeros((8,8))
matrice_bordo[::7] = 1
matrice_bordo[:,::7] = 1 # Solo un : per dire che voglio considerare tutte le righe

print(matrice_bordo)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


**2. Matrice a Scacchiera**

Crea una matrice 8x8 che abbia un pattern a scacchiera di 0 e 1. La casella in alto a sinistra (indice `[0,0]`) deve essere `1`.

*Suggerimento: Pensa a come lo slicing con `start:stop:step` possa aiutarti a selezionare tutti gli elementi in posizioni pari o dispari.*

In [34]:
# Il tuo codice qui
scacchiera = np.zeros((8, 8), dtype=int)
scacchiera[:,0::2] = 1 # Considero tutte le righe e modifico mettendo 1 alle colonne che sono in posizione pari
scacchiera[1::2,:] = 0 # Considero solo le righe in posizione dispari e metto 0 alle colonne
scacchiera[1::2,1::2] = 1 # Considero solo le righe in posizione dispari e considero le colonne in posizione dispari e metto 1
print(scacchiera)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**3. Impilare Array**

Crea due matrici 4x4, `A` e `B`, con numeri casuali.
a) Impilale **orizzontalmente** per creare una matrice 4x8.
b) Impilale **verticalmente** per creare una matrice 8x4.

*Info: Per questo esercizio puoi usare le funzioni `np.hstack()` e `np.vstack()`.*

In [35]:
# Il tuo codice qui
A = np.random.randint(0, 10, (4,4))
B = np.random.randint(0, 10, (4,4))

# a) Impilamento orizzontale
imp_orizzontale = np.hstack((A,B))
print("Impilamento orizzontale (4x8):\n", imp_orizzontale)

# b) Impilamento verticale
imp_verticale = np.vstack((A,B))
print("\nImpilamento verticale (8x4):\n", imp_verticale)

Impilamento orizzontale (4x8):
 [[9 4 2 6 4 0 8 5]
 [7 8 8 9 4 7 8 8]
 [2 0 6 7 2 6 2 8]
 [8 1 7 1 8 6 6 5]]

Impilamento verticale (8x4):
 [[9 4 2 6]
 [7 8 8 9]
 [2 0 6 7]
 [8 1 7 1]
 [4 0 8 5]
 [4 7 8 8]
 [2 6 2 8]
 [8 6 6 5]]


i**4. Normalizzare una Matrice**

Crea una matrice 5x5 di numeri casuali. Successivamente, calcola il valore minimo (`min`) e il valore massimo (`max`) dell'intera matrice. Crea una nuova matrice normalizzata in cui ogni elemento `x` è stato trasformato con la formula `(x - min) / (max - min)`. Il risultato dovrebbe essere una matrice con valori compresi tra 0 e 1.

In [36]:
# Il tuo codice qui
matrice_casuale = np.random.randint(0, 100, (5,5))
print("Originale:\n", matrice_casuale)
valore_massimo = matrice_casuale.max()
valore_minimo = matrice_casuale.min()
print("Valore massimo: ", valore_massimo)
print("Valore minimo: ", valore_minimo)
matrice_normalizzata = np.empty((5,5))
for i  in range(1,5):
    for j in range(1,5):
        matrice_normalizzata[i][j] = ((matrice_casuale[i][j] - valore_massimo)/ (valore_massimo - valore_minimo))

print("\nNormalizzata:\n", matrice_normalizzata)

Originale:
 [[22 11 12 92 96]
 [62 57 79 42 57]
 [97 50 45 40 89]
 [73 37  0 18 23]
 [ 3 29 16 84 82]]
Valore massimo:  97
Valore minimo:  0

Normalizzata:
 [[ 2.85743870e-315  0.00000000e+000  4.84592629e-317  4.83865364e-317
   6.33419666e-310]
 [ 6.33419679e-310 -4.12371134e-001 -1.85567010e-001 -5.67010309e-001
  -4.12371134e-001]
 [ 6.33419666e-310 -4.84536082e-001 -5.36082474e-001 -5.87628866e-001
  -8.24742268e-002]
 [ 6.33419665e-310 -6.18556701e-001 -1.00000000e+000 -8.14432990e-001
  -7.62886598e-001]
 [ 6.33419667e-310 -7.01030928e-001 -8.35051546e-001 -1.34020619e-001
  -1.54639175e-001]]


**5. Sostituzione Condizionata**

Crea una matrice 10x10 di numeri interi casuali tra 1 e 100. Sostituisci tutti i numeri maggiori di 50 con il valore `-1`.

*Suggerimento: La maschera booleana è tua amica!*

In [37]:
# Il tuo codice qui
matrice_cond = np.random.randint(1,100,(10,10))
maschera = matrice_cond > 50
# print(maschera)
matrice_cond[maschera] = -1
print(matrice_cond)

[[15 -1 -1 18 -1 -1 26 49 18 33]
 [-1 -1 42 -1 13 31 -1 18 17  1]
 [32 -1 -1 39 23 -1 -1 -1 -1 -1]
 [28 -1 -1 -1 49 -1 -1 -1 38 12]
 [22 34 -1 44 -1 -1 -1 41 44 -1]
 [-1  9 -1 -1 29 31 -1 26 -1 -1]
 [-1 -1 14 42 34  5 -1 -1 29 40]
 [-1 10  8 23 33  4 10 -1 -1 -1]
 [31 -1 -1 31 10  3 -1 14 -1 -1]
 [ 6 -1 -1 49 -1 43 35 41 47 33]]



### Sezione 2: Slicing e Indicizzazione di Livello Superiore

Per i prossimi esercizi, usa la seguente matrice 10x10.

In [38]:
mat_test_avanzata = np.arange(100).reshape(10, 10)
print(mat_test_avanzata)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


**6. Estrai l'Anti-Diagonale**

Estrai l'anti-diagonale della `mat_test_avanzata`, ovvero la linea di elementi che va dall'angolo in alto a destra a quello in basso a sinistra (i numeri 9, 18, 27, ..., 90).

*Suggerimento: Potresti prima "ribaltare" la matrice da sinistra a destra e poi usare un metodo che già conosci...*

In [39]:
# Il tuo codice qui
mat = mat_test_avanzata[::-1]
print(mat)
print("----")
anti_diagonale = mat.diagonal()
print(anti_diagonale)
print("----")
anti_diagonale = anti_diagonale[::-1]
print(anti_diagonale)
print("----")

[[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]
----
[90 81 72 63 54 45 36 27 18  9]
----
[ 9 18 27 36 45 54 63 72 81 90]
----


**8. I Quattro Angoli**

Estrai i 4 elementi agli angoli della `mat_test_avanzata` e mettili in un nuovo array 2x2.

In [40]:
# Il tuo codice qui
# Suggerimento: usa l'indicizzazione avanzata (fancy indexing) per selezionare righe e colonne specifiche.
angoli = mat_test_avanzata[[0,9]]
angoli = angoli[:,::9]
print(angoli)

[[ 0  9]
 [90 99]]


**9. Filtrare Righe basandosi su una Colonna**

Seleziona e stampa tutte le righe della `mat_test_avanzata` in cui il valore nella terza colonna (indice 2) è un multiplo di 5.

In [41]:
# Il tuo codice qui
colonna_due = mat_test_avanzata[:,2]
print(colonna_due)
maschera = colonna_due % 5 == 0
print(maschera)
risultato = mat_test_avanzata[maschera]
# Versione compatta : risultato = mat_test_avanzata[mat_test_avanzata[:,5] %5 === 0
print(risultato)

[ 2 12 22 32 42 52 62 72 82 92]
[False False False False False False False False False False]
[]


**10. Estrarre una "Croce"**

Estrai dalla `mat_test_avanzata` la 5ª riga (indice 4) e la 6ª colonna (indice 5).

In [42]:
# Il tuo codice qui
riga_4 = mat_test_avanzata[4::6]
colonna_5 = mat_test_avanzata[:,5::5]

print("Riga 4:", riga_4)
print("Colonna 5:", colonna_5)

Riga 4: [[40 41 42 43 44 45 46 47 48 49]]
Colonna 5: [[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]
 [65]
 [75]
 [85]
 [95]]


**11. Dividere una Matrice**

Dividi la `mat_test_avanzata` in 5 sotto-matrici orizzontali, ognuna di forma 2x10.

*Info: La funzione `np.vsplit()` potrebbe esserti utile.*

In [43]:
# Il tuo codice qui
sotto_matrici = np.split(mat_test_avanzata,5)

# Stampa la prima e l'ultima per verificare
print("Prima sotto-matrice:\n", sotto_matrici[0])
print("\nUltima sotto-matrice:\n", sotto_matrici[-1])

Prima sotto-matrice:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

Ultima sotto-matrice:
 [[80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



### Sezione 3: Modifica Avanzata con Viste e Broadcasting

**12. Moltiplicazione di Righe Alternate**

Nella `mat_test_avanzata`, moltiplica per `2` tutti gli elementi che si trovano nelle righe con indice pari (0, 2, 4, ...).

In [44]:
# Il tuo codice qui
# Lavora su una copia per non modificare la matrice per gli esercizi successivi
matrice_modificata = mat_test_avanzata.copy()

matrice_modificata = matrice_modificata[::2]*2
print(matrice_modificata)

[[  0   2   4   6   8  10  12  14  16  18]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 80  82  84  86  88  90  92  94  96  98]
 [120 122 124 126 128 130 132 134 136 138]
 [160 162 164 166 168 170 172 174 176 178]]


**13. Impostare a Zero un Blocco Interno**

Prendi la `mat_test_avanzata` e imposta a `0` tutti gli elementi del blocco interno 4x4 (escluso il bordo).

In [45]:
# Il tuo codice qui
matrice_con_buco = mat_test_avanzata.copy()
matrice_con_buco[3:7,3:7] = 0
print(matrice_con_buco)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32  0  0  0  0 37 38 39]
 [40 41 42  0  0  0  0 47 48 49]
 [50 51 52  0  0  0  0 57 58 59]
 [60 61 62  0  0  0  0 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


**14. Somma di Vettori a una Matrice**

Crea un vettore 1x10 con i numeri da 0 a 9. Somma questo vettore a **ciascuna riga** della `mat_test_avanzata`.

*Suggerimento: Il broadcasting farà la magia per te!*

In [46]:
# Il tuo codice qui
vettore = np.arange(0,10)
print(vettore)
risultato_somma = vettore + mat_test_avanzata[:]

print(risultato_somma)

[0 1 2 3 4 5 6 7 8 9]
[[  0   2   4   6   8  10  12  14  16  18]
 [ 10  12  14  16  18  20  22  24  26  28]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 30  32  34  36  38  40  42  44  46  48]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 50  52  54  56  58  60  62  64  66  68]
 [ 60  62  64  66  68  70  72  74  76  78]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 80  82  84  86  88  90  92  94  96  98]
 [ 90  92  94  96  98 100 102 104 106 108]]


**15. Scambio di Quadranti**

Scambia il quadrante 5x5 in alto a sinistra della `mat_test_avanzata` con quello in basso a destra.

*Suggerimento: Potrebbe essere necessario usare una variabile temporanea e delle copie per non perdere i dati durante lo scambio.*

In [47]:
# Il tuo codice qui
matrice_scambiata = mat_test_avanzata.copy()
matrice_1Q = matrice_scambiata[:5:,:5:].copy()
print(matrice_1Q)
print("----")
matrice_4Q = matrice_scambiata[5:10:,5:10:].copy()
print(matrice_4Q)
print("----")
matrice_scambiata[5:10:,5:10:] = matrice_1Q
matrice_scambiata[:5:,:5:] = matrice_4Q

print(matrice_scambiata)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
----
[[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]
----
[[55 56 57 58 59  5  6  7  8  9]
 [65 66 67 68 69 15 16 17 18 19]
 [75 76 77 78 79 25 26 27 28 29]
 [85 86 87 88 89 35 36 37 38 39]
 [95 96 97 98 99 45 46 47 48 49]
 [50 51 52 53 54  0  1  2  3  4]
 [60 61 62 63 64 10 11 12 13 14]
 [70 71 72 73 74 20 21 22 23 24]
 [80 81 82 83 84 30 31 32 33 34]
 [90 91 92 93 94 40 41 42 43 44]]



# Esercizi Finali su NumPy: Ufuncs, Aggregazioni e Broadcasting

Questa è la serie finale di esercizi per padroneggiare i calcoli con NumPy. Gli esercizi sono divisi in tre livelli di difficoltà.

Esegui la cella qui sotto per importare NumPy.

---
## Livello Base (10 Esercizi)

Questi esercizi coprono le operazioni fondamentali.

1. Crea un array da 0 a 10. Moltiplica ogni elemento per 3.

In [48]:

a = np.arange(0,10)
risultato_1 = a*3
print(risultato_1)

[ 0  3  6  9 12 15 18 21 24 27]


2. Crea un array con i valori[3.5, 1.2, 8.3, 4.0]. Aggiungi 10 a ogni elemento

In [49]:

b = np.array([3.5,1.2,8.3,4.0])
risultato_2 = b+10
print(risultato_2)

[13.5 11.2 18.3 14. ]


3. Crea un array 3x3 di tua scelta. Calcola il quadrato di ogni elemento.

In [55]:
c = np.random.randint(1,10,(3,3))
risultato_3 = c**2
print(risultato_3)

[[81 64 64]
 [49  9  1]
 [25 36 25]]


4. Crea un array con i seguenti angoli in radianti:[0, np.pi/2, np.pi]. Calcola il seno di ogni angolo.

In [56]:
# Il tuo codice qui
d = np.array([0,np.pi/2,np.pi])
risultato_4 = np.sin(d)
print(risultato_4)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


5. Crea un array 1D con 10 numeri interi casuali tra 1 e 50. Calcola la somma totale di tutti gli elementi.

In [57]:

e = np.random.randint(1,5,(10))
risultato_5 = np.sum(e)
print(f"Array: {e}, Somma: {risultato_5}")

Array: [3 3 2 1 1 4 1 3 3 1], Somma: 22


6. Crea una matrice 4x4 con numeri casuali. Trova il valore minimo e massimo dell'intera matrice.

In [60]:
# Il tuo codice qui
f = np.random.randint(1,100,(4,4))
minimo_6 = np.min(f)
massimo_6 = np.max(f)
print(f"Matrice:\n{f}\nMinimo: {minimo_6}, Massimo: {massimo_6}")

Matrice:
[[14  4 32 77]
 [88 18 30 70]
 [51 52 21  6]
 [71 62 17 75]]
Minimo: 4, Massimo: 88


7. Crea una matrice 3x5 di uni. Somma il numero 5 a ogni elemento usando il broadcasting.

In [62]:
# Il tuo codice qui
g = np.ones((3,5))
risultato_7 = g+5
print(risultato_7)

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


8. Crea un array 1D e calcola la media di tutti i suoi elementi.

In [63]:
# Il tuo codice qui
h = np.array([1, 5, 1, 10, 2, 1])
risultato_8 = np.mean(h)
print(risultato_8)

3.3333333333333335


9. Data la matrice dell'esercizio 6, calcola la somma di ogni colonna.

In [66]:
# Il tuo codice qui
# Usa la matrice 'f' creata nell'esercizio 6
risultato_9 = np.sum(g, axis = 0)
print(risultato_9)

[3. 3. 3. 3. 3.]


10. Data la matrice dell'esercizio 6, calcola la media di ogni riga.

In [67]:
# Il tuo codice qui
# Usa la matrice 'f' creata nell'esercizio 6
risultato_10 = np.mean(g,axis=1)
print(risultato_10)

[1. 1. 1.]


---
## Livello Medio (10 Esercizi)

Questi esercizi richiedono di combinare più concetti. Per i prossimi esercizi, usa la seguente matrice 5x5.

In [68]:
np.random.seed(0)
mat_media = np.random.randint(1, 101, (5, 5))
print("Matrice per esercizi di livello medio:\n", mat_media)

Matrice per esercizi di livello medio:
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]


11. Sottrai la media di ogni colonna dalla colonna stessa. (Questo processo è noto come "centrare" i dati).

In [70]:
# Il tuo codice qui
# Suggerimento: Calcola prima le medie delle colonne, poi usa il broadcasting.
media_colonne = np.mean(mat_media,axis = 0)
risultato_11 = mat_media - media_colonne
print(risultato_11)

[[ -9.8 -11.8   7.   19.4  -7.4]
 [-44.8  24.2 -36.  -11.6  12.6]
 [ 16.2  29.2  31.  -35.6 -16.4]
 [ 11.2 -19.8  30.   -1.6  13.6]
 [ 27.2 -21.8 -32.   29.4  -2.4]]


12. Trova la deviazione standard di ogni riga dellamat_media.

In [71]:
# Il tuo codice qui
risultato_12 = np.std(mat_media,axis=1)
print(risultato_12)

[10.14692072 32.052457   28.01713761 20.24845673 22.87006777]


13. Trova l'indice (la posizione) dell'elemento con il valore più alto nell'intera matricemat_media.

In [72]:
# Il tuo codice qui
risultato_13 = np.argmax(mat_media)
print(f"L'indice dell'elemento massimo è: {risultato_13}")

L'indice dell'elemento massimo è: 11


14. Conta quanti elementi nellamat_mediasono maggiori di 70.

In [75]:
# Il tuo codice qui
risultato_14 = np.sum(mat_media > 70)
print(f"Ci sono {risultato_14} elementi maggiori di 70.")

Ci sono 10 elementi maggiori di 70.


15. Crea un vettore 1D di 5 elementi. Aggiungilo a ogni riga dellamat_media(broadcasting).

In [76]:
# Il tuo codice qui
vettore_15 = np.arange(5)
risultato_15 = mat_media + vettore_15
print(risultato_15)

[[45 49 67 71 72]
 [10 85 24 40 92]
 [71 90 91 16 63]
 [66 41 90 50 93]
 [82 39 28 81 77]]


16. Calcola il prodotto di tutti gli elementi della diagonale principale dellamat_media.

In [77]:
# Il tuo codice qui
risultato_16 = np.prod(mat_media.diagonal())
print(risultato_16)

1154257020


17. Crea un vettore colonna di 5 elementi. Sommalo alla mat_media.

In [80]:
# Il tuo codice qui
vettore_17_riga = np.arange(5)
vettore_17_colonna = np.arange(1,6).reshape(5,1)
risultato_17 = vettore_17_riga + mat_media
print(risultato_17)

[[45 49 67 71 72]
 [10 85 24 40 92]
 [71 90 91 16 63]
 [66 41 90 50 93]
 [82 39 28 81 77]]


18. Sostituisci tutti gli elementi dispari dellamat_mediacon il valore -1.

In [81]:
# Il tuo codice qui
mat_copia_18 = mat_media.copy() # Lavora su una copia
maschera_18 = mat_copia_18% 2 != 0
mat_copia_18[maschera_18] = -1
print(mat_copia_18)

[[-1 48 -1 68 68]
 [10 84 22 -1 88]
 [-1 -1 -1 -1 -1]
 [66 40 88 -1 -1]
 [82 38 26 78 -1]]


19. Calcola la somma cumulativa degli elementi lungo le colonne dell'amat_media.

In [82]:
# Il tuo codice qui
risultato_19 = np.cumsum(mat_media, axis = 0)
print(risultato_19)

[[ 45  48  65  68  68]
 [ 55 132  87 105 156]
 [126 221 176 118 215]
 [192 261 264 165 304]
 [274 299 290 243 377]]


20. Normalizza lamat_media(sottrai la media e dividi per la deviazione standard dell'intera matrice).

In [83]:
# Il tuo codice qui
media_totale = np.mean(mat_media)
std_totale = np.std(mat_media)
risultato_20 = (mat_media - media_totale)/std_totale
print(risultato_20)

[[-0.58068698 -0.45903468  0.23032836  0.35198066  0.35198066]
 [-1.99996382  1.00079293 -1.51335462 -0.90509312  1.16299599]
 [ 0.47363296  1.20354676  1.20354676 -1.87831152 -0.01297625]
 [ 0.27087912 -0.78344082  1.16299599 -0.49958545  1.20354676]
 [ 0.91969139 -0.86454235 -1.35115155  0.75748833  0.55473449]]


---
## Livello Complesso (10 Esercizi)

Questi esercizi richiedono un ragionamento più profondo e la combinazione di più tecniche. Per i prossimi esercizi, usa questa matrice 10x10.

In [84]:
np.random.seed(42)
mat_complessa = np.random.randint(0, 100, (10,10))
print("Matrice per esercizi complessi:\n", mat_complessa)

Matrice per esercizi complessi:
 [[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]


21. Trova la riga con la somma degli elementi più alta.

In [90]:
# Il tuo codice qui
somme_righe = np.sum(mat_complessa, axis=1)
indice_riga_max = np.argmax(somme_righe)
riga_max = mat_complessa[indice_riga_max]
print(f"La riga con la somma più alta (indice {indice_riga_max}) è: \n{riga_max}")

La riga con la somma più alta (indice 9) è: 
[71 77 86 61 39 84 79 81 52 23]


22. Calcola la distanza Euclidea tra due vettori 1D di 10 elementi ciascuno.

In [91]:
# Il tuo codice qui
a = np.arange(10)
b = np.arange(10, 0, -1)
distanza_22 = np.sqrt(np.sum((a-b)**2))
print(distanza_22)

18.439088914585774


23. Crea una matrice di distanze: data una matrice 10x2 di punti (x,y), calcola la distanza di ogni punto da ogni altro punto.

In [92]:
# Il tuo codice qui
punti = mat_complessa[:10, :2] # Usiamo le prime 10 righe e 2 colonne
distanze = np.sqrt(np.sum((punti[:, np.newaxis, :] - punti[np.newaxis, :, :]) ** 2, axis=-1))
print(distanze.shape) # Dovrebbe essere (10, 10)

(10, 10)


24. Sostituisci tutti gli elementi in un raggio di 20 dal valore massimo dellamat_complessacon il valore 0.

In [96]:
# Il tuo codice qui
mat_copia_24 = mat_complessa.copy()
massimo_24 = np.argmax(mat_complessa)
i,j = np.unravel_index(massimo_24, mat_complessa.shape)

y,x = np.ogrid[:mat_complessa.shape[0], :mat_complessa.shape[1]]

maschera = np.sqrt((x-j)**2 + (y-i)**2) < 20

mat_copia_24[maschera] = 0
print(mat_copia_24)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


25. Crea un array 1D V di 10 elementi. Crea una matrice 10x10 la cui i-esima riga è v + i.

In [99]:
# Il tuo codice qui
v = np.arange(10)
i = np.arange(10).reshape(10,1)
risultato_25 = v + i[:,np.newaxis]
print(risultato_25)

[[[ 0  1  2  3  4  5  6  7  8  9]]

 [[ 1  2  3  4  5  6  7  8  9 10]]

 [[ 2  3  4  5  6  7  8  9 10 11]]

 [[ 3  4  5  6  7  8  9 10 11 12]]

 [[ 4  5  6  7  8  9 10 11 12 13]]

 [[ 5  6  7  8  9 10 11 12 13 14]]

 [[ 6  7  8  9 10 11 12 13 14 15]]

 [[ 7  8  9 10 11 12 13 14 15 16]]

 [[ 8  9 10 11 12 13 14 15 16 17]]

 [[ 9 10 11 12 13 14 15 16 17 18]]]


26. Trova la colonna nellamat_complessache ha la più alta correlazione con un vettore casuale di 10 elementi.
Info: La correlazione tra due vettori x e y è sum((x - x.mean()) * (y - y.mean())) / (len(x) * x.std() * y.std()).


In [ ]:
def correlazione(x, y):
    return np.sum((x - x.mean()) * (y - y.mean())) / (len(x) * x.std() * y.std())

vettore_casuale_26 = np.random.rand(10)
# Calcola correlazione per ogni colonna
correlazioni = [correlazione(mat_complessa[:, i], vettore_casuale_26) for i in range(mat_complessa.shape[1])]

# Trova l'indice della colonna con correlazione massima
indice_col_max = np.argmax(correlazioni)

print(f"La colonna con la correlazione più alta è la numero {indice_col_max}")

27. Moltiplica la mat_complessa per un vettore colonna di 10 elementi (broadcasting).

In [100]:
# Il tuo codice qui
v_col_27 = np.arange(10).reshape(10,1)
risultato_27 = mat_complessa * v_col_27
print(risultato_27)

[[  0   0   0   0   0   0   0   0   0   0]
 [ 87  99  23   2  21  52   1  87  29  37]
 [  2 126 118  40  64 150 114  42 176  96]
 [270 174 123 273 177 237  42 183 183 138]
 [244 200 216 252   8 200  24  80 288 152]
 [ 85  15 440 295  65  40 445 260   5 415]
 [546 354 420 258  42 276 204 462 480 210]
 [343  21   7  35 371  21 371 644 434 119]
 [712 344 264 584 488 792 104 752 376 112]
 [639 693 774 549 351 756 711 729 468 207]]


28. Trova i 5 valori più grandi presenti nellamat_complessa.
Suggerimento: np.sort o np.partition potrebbero essere utili.


In [104]:
# Il tuo codice qui
risultato_28 = np.sort(mat_complessa.flatten())[-5:]
print(risultato_28)

[92 92 94 99 99]


29. Calcola la media mobile a 3 elementi per ogni colonna dellamat_complessa.
Suggerimento: È una sfida. Potresti fare uno slicing per prendere le righe i, i+1, i+2, sommarle e dividerle per 3, iterando.

In [ ]:
risultato_29 = np.zeros((8, mat_complessa.shape[1]))

for i in range(8):  # 8 perché facciamo la media di 3 elementi alla volta (10-3+1)
    risultato_29[i] = mat_complessa[i:i+3].mean(axis=0)


30. Sottrai ad ogni riga dellamat_complessala media di quella stessa riga.

In [103]:
# Il tuo codice qui
risultato_30 = mat_complessa - mat_complessa.mean(axis =1)[:,np.newaxis]
print(risultato_30.mean(axis=1)) # Dovrebbe essere un array di zeri (o quasi)

[ 1.42108547e-15  2.84217094e-15  1.42108547e-15  0.00000000e+00
 -1.42108547e-15  2.84217094e-15 -2.84217094e-15  2.84217094e-15
 -1.42108547e-15  2.84217094e-15]
